### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not int

### ISSUE THREAD

**Issue by doomedraven** [spender-sandbox/cuckoo-modified#103]
got it few times from last night, at the moment can't say which sample produce that as it was in bulk processing

````
2016-04-28 12:52:35,427 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Static":
Traceback (most recent call last):
  File "/opt/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/opt/cuckoo-modified/utils/../modules/processing/static.py", line 1432, in run
    static = PortableExecutable(self.file_path, self.results).run()
  File "/opt/cuckoo-modified/utils/../modules/processing/static.py", line 766, in run
    peresults["exported_dll_name"] = self._get_exported_dll_name()
  File "/opt/cuckoo-modified/utils/../modules/processing/static.py", line 345, in _get_exported_dll_name
    return convert_to_printable(self.pe.get_string_at_rva(self.pe.DIRECTORY_ENTRY_EXPORT.struct.Name))
  File "/opt/cuckoo-modified/utils/../lib/cuckoo/common/utils.py", line 137, in convert_to_printable
    if is_printable(s):
  File "/opt/cuckoo-modified/utils/../lib/cuckoo/common/utils.py", line 110, in is_printable
    if c not in PRINTABLE_CHARACTERS:
TypeError: 'in <string>' requires string as left operand, not int
```

**Comment by spender-sandbox** [comment]
Are you running the latest pefile?  It's broken, you should use a version from last year.

-Brad

**Comment by doomedraven** [comment]
did fresh install yesterday, and did __git pull__ after few your fresh pushes

**Comment by spender-sandbox** [comment]
That's orthogonal to my question :)

-Brad

**Comment by doomedraven** [comment]
sorry not saw __pefile__

pip freeze | grep pefile
pefile==2016.3.28

**Comment by spender-sandbox** [comment]
Yep, that's the bad version, use something from last year (shouldn't matter much which one, there wasn't much activity then).  This year there's a lot of code churn and introduced bugs.

-Brad

**Comment by doomedraven** [comment]
oh ok, thanks :)
