### ISSUE TITLE
requirements.txt contains incompatible version of bson

### ISSUE THREAD

**Issue by Magicked** [spender-sandbox/cuckoo-modified#115]
Running pip install -r requirements.txt throws the following error:

```
Downloading/unpacking bson (from -r requirements.txt (line 2))
  Downloading bson-1.1.0.tar.gz
  Running setup.py (path:/home/cuckoo/env/build/bson/setup.py) egg_info for package bson
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/cuckoo/env/build/bson/setup.py", line 24, in <module>
        import bson
      File "bson/__init__.py", line 66, in <module>
        from . import codec
      File "bson/codec.py", line 28, in <module>
        from .objects import *
      File "bson/objects.py", line 36
        class BSONObject(object, metaclass=ABCMeta):
                                          ^
    SyntaxError: invalid syntax
```

According to https://api.mongodb.org/python/current/installation.html, there is no need to install bson as it is incompatible with pymongo. pymongo includes its own version.

**Comment by doomedraven** [comment]
you can install it with apt-get install python-bson, i specified this fail on that merge

**Comment by seanthegeek** [comment]
Whoops, that was my commit. It's fixed now.
