### ISSUE TITLE
import missing in retention.py?

### ISSUE THREAD

**Issue by mallorybobalice** [spender-sandbox/cuckoo-modified#149]
modules/reporting/retention.py needs an extra import.
 
from bson.objectid import ObjectId

2016-05-23 18:29:15,860 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "Retention":
Traceback (most recent call last):
  File "kittenscsb1utils/../lib/cuckoo/core/plugins.py", line 628, in process
    current.run(self.results)
  File "kittenscsb1utils/../modules/reporting/retention.py", line 204, in run
    delete_mongo_data(curtask, lastTask)
  File "kittenscsb1utils/../modules/reporting/retention.py", line 60, in delete_mongo_data
    results_db.analysis.remove({"_id": ObjectId(analysis["_id"])})
NameError: global name 'ObjectId' is not defined

**Comment by mallorybobalice** [comment]
or is this the odd bit where I've accidentally previously installed bson separately, then realized my mistake, reinstalled the right version but at the same didn't follow the use the bundled pymongo? one

**Comment by KillerInstinct** [comment]
Yes, object ID is in Mongos version of BSON. Make sure you have pip uninstalled bson, mongodb and then pip install mongodb (or w/e the pip package is called)
