### ISSUE TITLE
Key Error in pdf-eof sig processing

### ISSUE THREAD

**Issue by geudrik** [spender-sandbox/cuckoo-modified#162]
```
Traceback (most recent call last):
  File "/opt/cuckoo/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 351, in process
    data = current.run()
  File "/opt/cuckoo/cuckoo-modified/utils/../modules/signatures/pdf_eof.py", line 31, in run
    if "Data After EOF" in self.results["static"]["Info"]:
KeyError: 'Info'
2016-05-31 06:50:43,744 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "pdf_page":
Traceback (most recent call last):
  File "/opt/cuckoo/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 351, in process
    data = current.run()
  File "/opt/cuckoo/cuckoo-modified/utils/../modules/signatures/pdf_page.py", line 31, in run
    if "/Page" in self.results["static"]["Streams"]:
KeyError: 'Streams'
```

**Comment by geudrik** [comment]
Additional key errors in other processing modules

```
Traceback (most recent call last):
  File "/opt/cuckoo/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 351, in process
    data = current.run()
  File "/opt/cuckoo/cuckoo-modified/utils/../modules/signatures/copies_self.py", line 39, in run
    for drop in self.results["dropped"]:
KeyError: 'dropped'
2016-05-31 06:54:22,943 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "polymorphic":
Traceback (most recent call last):
  File "/opt/cuckoo/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 351, in process
    data = current.run()
  File "/opt/cuckoo/cuckoo-modified/utils/../modules/signatures/polymorphic.py", line 45, in run
    for drop in self.results["dropped"]:
KeyError: 'dropped'
2016-05-31 06:54:22,975 [requests.packages.urllib3.connectionpool] INFO: Starting new HTTPS connection (1): www.virustotal.com
2016-05-31 06:54:23,743 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "copies_self":
Traceback (most recent call last):
  File "/opt/cuckoo/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 351, in process
    data = current.run()
  File "/opt/cuckoo/cuckoo-modified/utils/../modules/signatures/copies_self.py", line 39, in run
    for drop in self.results["dropped"]:
KeyError: 'dropped'
2016-05-31 06:54:23,767 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "polymorphic":
Traceback (most recent call last):
  File "/opt/cuckoo/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 351, in process
    data = current.run()
  File "/opt/cuckoo/cuckoo-modified/utils/../modules/signatures/polymorphic.py", line 45, in run
    for drop in self.results["dropped"]:
KeyError: 'dropped'
```

**Comment by doomedraven** [comment]
i was also pushed patched(key check) for polymorphic and copies_self, but they never was accepted

**Comment by KillerInstinct** [comment]
The PDF issue is because that signature was deleted, and added back in properly to a generic static analysis signature:
https://github.com/spender-sandbox/community-modified/blob/master/modules/signatures/static_pdf.py

(just make sure you update your sigs properly)

As far as the dropped key error, do you have the dropped processing module enabled? If so, if there are no dropped files it should return an empty list to the key element of "dropped" and thus that error should only exist if you have other issues. Let us know what those may be.

**Comment by doomedraven** [comment]
in my case is that, i have enabled and if no dropped than exception, but with .get("dropped", []) would be just ignored and more pretty see logs

**Comment by KillerInstinct** [comment]
I don't see how the key wouldn't get created though.

The dropped key gets created in the results here in a processing module executes and returns successfully:
https://github.com/spender-sandbox/cuckoo-modified/blob/e135915f1eac20a38a173a108614fe9f7dd661a4/lib/cuckoo/core/plugins.py#L208
(if you have an exception in the processing module it would be printed there)

In the dropped module, we initialize an empty list to be returned:
https://github.com/spender-sandbox/cuckoo-modified/blob/master/modules/processing/dropped.py#L57

I have several analysis with no dropped files that don't create errors in those signatures.

**Comment by doomedraven** [comment]
no idea, but i'm not alone who getting this exception, will get a look on that later

**Comment by doomedraven** [comment]
lol now when im hunting for that errors, i can't reproduce them :D
