### ISSUE TITLE
error in pcap

### ISSUE THREAD

**Issue by limited-root** [spender-sandbox/cuckoo-modified#172]
`[Processing.Pcap] ERROR: Failed to process packet: 'type'
Traceback (most recent call last):
  File "/etc/cuckoo/modules/processing/network.py", line 630, in run
    self._udp_dissect(connection, udp.data)
  File "/etc/cuckoo/modules/processing/network.py", line 235, in _udp_dissect
    self._add_dns(data)
  File "/etc/cuckoo/modules/processing/network.py", line 388, in _add_dns
    reqtuple = query["type"], query["request"]
KeyError: 'type'`

**Comment by KillerInstinct** [comment]
Try adding this commit, it looks related:
https://github.com/cuckoosandbox/cuckoo/commit/18f114681c855fd9f62dbf9146effbb9868d5b9d
