### ISSUE TITLE
Cuckoo api socket error

### ISSUE THREAD

**Issue by masifpak** [spender-sandbox/cuckoo-modified#188]
From two days, when I start cuckoo api.py, it run but it do not receive any malware but when cancell the process it receive malware and prompt the below error. What problem can be?

```
Exception happened during processing of request from ('172.20.16.36', 42772)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 116, in handle
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
----------------------------------------
172.20.16.36 - - [29/Jun/2016 00:08:03] "POST /tasks/create/file HTTP/1.1" 200 37
```

**Comment by doomedraven** [comment]
why you use api.py instead of integrated into webgui api in /api/ ? jsut to have more clear

**Comment by doomedraven** [comment]
i have api.py started few days with testing distributed and not have any issue

**Comment by masifpak** [comment]
I use api.py -H 0.0.0.0, so that i can submit malwares from remote machine. If there are other ways please let me know. Moreover what is webgui api?

**Comment by doomedraven** [comment]
there you have one inside of webgui, you just need adjust it in config/api.conf reqs per seg/min and which api you want to activate for users

<img width="766" alt="screen shot 2016-06-28 at 22 06 27" src="https://cloud.githubusercontent.com/assets/1856495/16430584/971b225c-3d7c-11e6-98cf-453b4e51519c.png">

**Comment by masifpak** [comment]
it is by default yes. Then how to send malware from remote machine and on which port.

**Comment by doomedraven** [comment]
`curl http://cuckoo/api/create/file file=@path_to_file`

you have examples inside on that tab

**Comment by doomedraven** [comment]
you may need add port number, everything depend how your django started

**Comment by masifpak** [comment]
Its working. but problem is we were using api.py for more than one year. what happen now. I prepare new machine but problem is still there. Any clue?

**Comment by doomedraven** [comment]
how frequently you getting this issue?

**Comment by masifpak** [comment]
On each submit. I was using this script

```
import requests
import json
REST_URL = "http://IP:8090/tasks/create/file"
#SAMPLE_FILE = "/home/aserg/binaries/2ddac459031504779cac2d9804a394f7"
SAMPLE_FILE = "/home/aserg/mal/def10b46791c58e0c1808f311046c173"
with open(SAMPLE_FILE, "rb") as sample:
    multipart_file = {"file": ("tmp", sample)}
    request = requests.post(REST_URL, files=multipart_file)
print request.text
```

**Comment by masifpak** [comment]
I also used this methon from same machine but no to avail.                                                          sudo curl -F file=@/home/itsec/78c9042bbcefd65beaa0d40386da9f89.exe http://172.20.16.30:8090/tasks/create/file/

**Comment by doomedraven** [comment]
did you try restart api.py?

**Comment by masifpak** [comment]
I tried many times. Any way can you guide me how can i control reqs per sec/min. And one last thing did you successfully tested cuckoo in distribution mode. i think it is not available in cuckoo-modified. I tried it on original cuckoo but facing some problem.

https://github.com/cuckoosandbox/cuckoo/issues/965#issuecomment-228595421

**Comment by doomedraven** [comment]
1) see https://github.com/spender-sandbox/cuckoo-modified/blob/master/conf/api.conf
2) yes and see https://github.com/spender-sandbox/cuckoo-modified/issues/187

**Comment by masifpak** [comment]
but there are confusing. e.g if i set rps = 60s and  rpm = 5/m  which will be preferred?

I have an APP which send malwares to analyze. I sends in bulk. Cuckoo tag them pending and process periodically. But when 2 or 3 malwares go in processing phase (after successful analysis) the whole system stuck. Can we control it? I mean there should be always one malware in running and maximum one in processing phase. Normally one malware take 8 to 10 minuts. Is this time normal.

**Comment by doomedraven** [comment]
if you don't care, `also there ratelimit in api.conf yes/no`
<img width="530" alt="screen shot 2016-06-29 at 11 25 23" src="https://cloud.githubusercontent.com/assets/1856495/16447306/30b50ddc-3dec-11e6-8aa5-0cf1e4721115.png">

it stucked bcz you configured it in bad way, but is now totally not related to issue

**Comment by KillerInstinct** [comment]
@masifpak Both rates per minute and rates per second are enforced, so if exceed either limit then the API will return an error. This allows to to have more granular limits, for example if you didn't want someone pulling full reports more than 4 times a minute, but wanted them to be able to pull two reports back to back, you could set it to be 4RPM and 1RPS.
