### ISSUE TITLE
Unable to connect to esx hypervisor

### ISSUE THREAD

**Issue by pkernevez** [spender-sandbox/cuckoo-modified#199]
Hi,

The commit 275a761e6efb59aa13b0b4a49e9bb45dae93d9be created a regression on the esx connector : we are not able to connect to the esx any more.
This is due to the signature of the method LibVirtMachinery._connect() that changed (now requires a parameter 'Label'), but the signature of esx child (and may be other connectors) has not changed 
https://github.com/spender-sandbox/cuckoo-modified/blob/master/modules/machinery/esx.py#L41

The error is produced on line 535 and 470 :
 https://github.com/spender-sandbox/cuckoo-modified/blob/master/lib/cuckoo/common/abstracts.py#L535
https://github.com/spender-sandbox/cuckoo-modified/blob/master/lib/cuckoo/common/abstracts.py#L470

**Comment by KillerInstinct** [comment]
FWF you should really be using the vSphere machinery now instead of esx.

**Comment by villain** [comment]
what if you dont have a vsphere instance? just performed a git pull and also seeing this

**Comment by mallorybobalice** [comment]
heh. vsphere can do memory dumps. esxi alone can't (well, there's not underlying libvirt support ). i'm not entirely certain why it's not possible to download a memory image taken as part of the snapshot via esxi api but i suppose not everyone needs it. 
I too need esxi machinery fixed.

**Comment by mallorybobalice** [comment]
hmm, ok thank you KI. I'll give it a try tomorrow. (it looks like the configs are essentially identical except for the connection info which is very similar and will take 5 mins to change) 
@KillerInstinct - would you mind expanding just a bit more. What specific licensing is required or enabling vsphere api on esxi (edition of ESXI or separate feature?) . that last bit sounds like it's already enabled on most instances where people are using esxi api? (or have the esxi server connected to an existing vcenter?) 

in any case I'll give mine a try :) thanks again for clearing it up

**Comment by KillerInstinct** [comment]
libvirt and pyvmomi access ESXi/vCenter through the vSphere API which is typically not free (you can get trail license.

You can use the vSphere machinery to connect to an ESXi host or to a vCenter host. ESXi is one product of the overall VMware vSphere product line. Both vCenter and ESXi have a vSphere API if licensed. As far as I remember, the vSphere API is not free, but of course you can get trial licenses.

Reference:
Licensing
Access to the vSphere API is governed by the variousvSphere Editions which provides both read and write access to the API. If you are using vSphere Hypervisor (free edition of ESXi), the vSphere API will only be available as read-only.

Source:
https://blogs.vmware.com/vsphere/2012/02/introduction-to-the-vsphere-api-part-1.html

**Comment by villain** [comment]
using the vsphere machinery, any idea what would be causing:

2016-07-04 11:18:00,875 [lib.cuckoo.core.scheduler] INFO: Using "vsphere" machine manager with max_analysis_count=0, max_machines_count=0, and max_vmstartup_count=10
Traceback (most recent call last):
  File "./cuckoo.py", line 132, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "./cuckoo.py", line 78, in cuckoo_main
    sched.start()
  File "/home/cuckoo/cuckoo-sandbox/lib/cuckoo/core/scheduler.py", line 565, in start
    self.initialize()
  File "/home/cuckoo/cuckoo-sandbox/lib/cuckoo/core/scheduler.py", line 533, in initialize
    machinery.initialize(machinery_name)
  File "/home/cuckoo/cuckoo-sandbox/lib/cuckoo/common/abstracts.py", line 97, in initialize
    self._initialize_check()
  File "/home/cuckoo/cuckoo-sandbox/modules/machinery/vsphere.py", line 88, in _initialize_check
    sslContext = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'

when trying to start cuckoo?

**Comment by jgajek** [comment]
The read-only API on the standalone ESXi host (i.e. one without a vSphere license) is sufficient to run the vSphere machinery for Cuckoo.  I have been using a free edition ESXi 5.1 host in this way for many months now.
