### ISSUE TITLE
Analysis timeout

### ISSUE THREAD

**Issue by exp0se** [spender-sandbox/cuckoo-modified#201]
I was running a setup a few weeks ago and everything was fine, but after pulling latest changes I am constantly hitting an analysis timeout. Not sure what changes could affect those?

My setup is:

ubuntu 16.04 + virtualbox + commit https://github.com/spender-sandbox/cuckoo-modified/commit/b6921078918871038362ee4c53afc5fc7dd9c0cf 

The previous commit i was running is 757c3fd66355a9b060c88e4b8e6853f98e02bc0b

For the most part analysis is complete, but typically lacking MISP data and yara. I've updated an agent in VM as per direction from latest changes.

I've tried to rollback on working copy with old agents, but it didn't work for some reason. I've also tried to double a timeout - didn't help as well.

Here is log example:
```
2016-03-06 01:48:49,000 [root] INFO: Date set to: 03-06-16, time set to: 09:48:49
2016-03-06 01:48:49,015 [root] DEBUG: Starting analyzer from: C:\mbyagius
2016-03-06 01:48:49,015 [root] DEBUG: Storing results at: C:\wRVXBUGKQ
2016-03-06 01:48:49,015 [root] DEBUG: Pipe server name: \\.\PIPE\uKHSQqI
2016-03-06 01:48:49,015 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2016-03-06 01:48:49,015 [root] INFO: Automatically selected analysis package "exe"
2016-03-06 01:48:49,140 [root] DEBUG: Started auxiliary module Browser
2016-03-06 01:48:49,140 [modules.auxiliary.digisig] INFO: Skipping authenticode validation, signtool.exe was not found in bin/
2016-03-06 01:48:49,140 [root] DEBUG: Started auxiliary module DigiSig
2016-03-06 01:48:49,140 [root] DEBUG: Started auxiliary module Disguise
2016-03-06 01:48:49,140 [root] DEBUG: Started auxiliary module Human
2016-03-06 01:48:49,140 [root] DEBUG: Started auxiliary module Screenshots
2016-03-06 01:48:49,140 [root] DEBUG: Started auxiliary module Usage
2016-03-06 01:48:49,171 [lib.api.process] INFO: Successfully executed process from path "C:\DOCUME~1\JOHN~1.MCL\LOCALS~1\Temp\corebot_dump.exe" with arguments "" with pid 2000
2016-03-06 01:48:49,203 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2016-03-06 01:48:49,233 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 2000
2016-03-06 01:48:51,233 [lib.api.process] INFO: Successfully resumed process with pid 2000
2016-03-06 01:48:51,233 [root] INFO: Added new process to list with pid: 2000
2016-03-06 01:48:51,358 [root] INFO: Cuckoomon successfully loaded in process with pid 2000.
2016-03-06 01:48:51,515 [root] INFO: Announced 32-bit process name: drwtsn32.exe pid: 116
2016-03-06 01:48:51,530 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2016-03-06 01:48:51,530 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 116
2016-03-06 01:48:51,530 [root] INFO: Disabling sleep skipping.
2016-03-06 01:48:51,592 [root] INFO: Disabling sleep skipping.
2016-03-06 01:48:51,608 [root] INFO: Added new process to list with pid: 116
2016-03-06 01:48:51,608 [root] INFO: Cuckoomon successfully loaded in process with pid 116.
2016-03-06 01:48:51,655 [root] INFO: Added new file to list with path: C:\Documents and Settings\All Users\Application Data\Microsoft\Dr Watson\drwtsn32.log
2016-03-06 01:49:21,905 [root] INFO: Notified of termination of process with pid 2000.
2016-03-06 01:49:22,233 [root] INFO: Added new file to list with path: C:\Documents and Settings\All Users\Application Data\Microsoft\Dr Watson\user.dmp
2016-03-06 01:49:22,750 [root] INFO: Notified of termination of process with pid 116.
2016-03-06 01:49:23,233 [root] INFO: Process with pid 2000 has terminated
2016-03-06 01:49:24,250 [root] INFO: Process with pid 116 has terminated
2016-03-06 01:49:43,265 [root] INFO: Process list is empty, terminating analysis.
2016-03-06 01:49:44,265 [root] INFO: Created shutdown mutex.
2016-03-06 01:49:45,265 [root] INFO: Shutting down package.
2016-03-06 01:49:45,265 [root] INFO: Stopping auxiliary modules.
2016-03-06 01:49:45,265 [root] INFO: Finishing auxiliary modules.
2016-03-06 01:49:45,265 [root] INFO: Shutting down pipe server and dumping dropped files.
2016-03-06 01:49:45,296 [root] INFO: Analysis completed.
```

Here is console output:
```
 2016-07-04 12:48:50,544 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/tmp/cuckoo-tmp/upload_jNXCyn/corebot_dump.exe" (task=41)
2016-07-04 12:48:50,599 [lib.cuckoo.core.scheduler] INFO: Task #41: acquired machine cuckoo1 (label=cuckoo1)
2016-07-04 12:48:52,509 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 24390 (interface=vboxnet0, host=192.168.56.3, dump path=/home/cuckoo/cuckoo-modified/storage/analyses/41/dump.pcap)
2016-07-04 12:48:52,510 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.3)
2016-07-04 12:55:08,767 [lib.cuckoo.core.scheduler] ERROR: The analysis hit the critical timeout, terminating.
2016-07-04 12:55:11,489 [requests.packages.urllib3.connectionpool] INFO: Starting new HTTPS connection (1): www.virustotal.com
2016-07-04 12:55:14,253 [requests.packages.urllib3.connectionpool] INFO: Starting new HTTPS connection (1): 10.0.180.18
2016-07-04 12:55:14,313 [requests.packages.urllib3.connectionpool] INFO: Starting new HTTPS connection (1): 10.0.180.18
2016-07-04 12:55:22,570 [lib.cuckoo.core.scheduler] INFO: Task #41: reports generation completed (path=/home/cuckoo/cuckoo-modified/storage/analyses/41)
2016-07-04 12:55:22,586 [lib.cuckoo.core.scheduler] INFO: Task #41: analysis procedure completed
```

**Comment by doomedraven** [comment]
increase timeout in conf/cuckoo.conf if you need highest timeout, some sample not exit between timeout reached, so it hitting timeout to not hijack vm for a while, just that :)

**Comment by exp0se** [comment]
Well, I tested it with the same samples, that i was running before the changes. They never hit a timeout before.

Plus, I tried to set a 5 min timeout and it still hitting it, which is definitelly not normal, escpecially for every sample i throw at it.

**Comment by spender-sandbox** [comment]
There may be a bug with the agent.py changes then.  Just above this line:
https://github.com/spender-sandbox/cuckoo-modified/blob/c4155c03f125c2685c3e4139c7bd9b5ff6a069ca/analyzer/windows/analyzer.py#L1176

Can you add a:
log.info("Completion key is %s", completion_key)

and give me the new analysis.log?

-Brad

**Comment by exp0se** [comment]
Brad,

I just re run the analysis with the same file, but I don't see this new log string at all.

I've modified the code like this:
```
        server = xmlrpclib.Server("http://127.0.0.1:8000")
        completion_key = self.config.get_options().get("completion_key", "")
        log.info("Completion key is %s", completion_key)
        server.complete(success, error, completion_key)
```

**Comment by spender-sandbox** [comment]
It should be in the analysis.log.  Can you add a:
log.info("Testing")
just before the self.config line?

-Brad

**Comment by exp0se** [comment]
It worked with Testing line, but completion key is not shown:
```
2016-03-06 06:39:41,000 [root] INFO: Date set to: 03-06-16, time set to: 14:39:41
2016-03-06 06:39:41,000 [root] DEBUG: Starting analyzer from: C:\rfofpepbs
2016-03-06 06:39:41,000 [root] DEBUG: Storing results at: C:\rozEkuDjD
2016-03-06 06:39:41,000 [root] DEBUG: Pipe server name: \\.\PIPE\xfolnYDgm
2016-03-06 06:39:41,000 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2016-03-06 06:39:41,000 [root] INFO: Automatically selected analysis package "exe"
2016-03-06 06:39:41,687 [root] DEBUG: Started auxiliary module Browser
2016-03-06 06:39:41,703 [modules.auxiliary.digisig] INFO: Skipping authenticode validation, signtool.exe was not found in bin/
2016-03-06 06:39:41,703 [root] DEBUG: Started auxiliary module DigiSig
2016-03-06 06:39:41,703 [root] DEBUG: Started auxiliary module Disguise
2016-03-06 06:39:41,703 [root] DEBUG: Started auxiliary module Human
2016-03-06 06:39:41,703 [root] DEBUG: Started auxiliary module Screenshots
2016-03-06 06:39:41,703 [root] DEBUG: Started auxiliary module Usage
2016-03-06 06:39:41,780 [lib.api.process] INFO: Successfully executed process from path "C:\Users\ARTUR~1.DON\AppData\Local\Temp\corebot_dump.exe" with arguments "" with pid 1548
2016-03-06 06:39:41,780 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2016-03-06 06:39:42,155 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 1548
2016-03-06 06:39:44,155 [lib.api.process] INFO: Successfully resumed process with pid 1548
2016-03-06 06:39:44,155 [root] INFO: Added new process to list with pid: 1548
2016-03-06 06:39:44,342 [root] INFO: Cuckoomon successfully loaded in process with pid 1548.
2016-03-06 06:44:43,155 [root] INFO: Analysis timeout hit, terminating analysis.
2016-03-06 06:44:43,155 [root] INFO: Created shutdown mutex.
2016-03-06 06:44:44,155 [root] INFO: Shutting down package.
2016-03-06 06:44:44,155 [root] INFO: Stopping auxiliary modules.
2016-03-06 06:44:44,655 [root] INFO: Finishing auxiliary modules.
2016-03-06 06:44:44,655 [root] INFO: Shutting down pipe server and dumping dropped files.
2016-03-06 06:44:44,655 [root] INFO: Analysis completed.
2016-03-06 06:44:44,655 [root] INFO: Testing
```

**Comment by spender-sandbox** [comment]
Ok, can you try repeating the completion_key = and log.info() lines at this location:
https://github.com/spender-sandbox/cuckoo-modified/blob/c4155c03f125c2685c3e4139c7bd9b5ff6a069ca/analyzer/windows/analyzer.py#L795

**Comment by exp0se** [comment]
Repeating worked, but it's blank
```
2016-06-22 12:03:23,030 [root] INFO: Completion key is 
2016-03-06 07:00:31,000 [root] INFO: Date set to: 03-06-16, time set to: 15:00:31
2016-03-06 07:00:31,000 [root] DEBUG: Starting analyzer from: C:\zwldc
2016-03-06 07:00:31,000 [root] DEBUG: Storing results at: C:\wWVBbN
2016-03-06 07:00:31,000 [root] DEBUG: Pipe server name: \\.\PIPE\sRwDuJXZFv
2016-03-06 07:00:31,015 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2016-03-06 07:00:31,015 [root] INFO: Automatically selected analysis package "exe"
2016-03-06 07:00:31,125 [root] DEBUG: Started auxiliary module Browser
2016-03-06 07:00:31,125 [modules.auxiliary.digisig] INFO: Skipping authenticode validation, signtool.exe was not found in bin/
2016-03-06 07:00:31,125 [root] DEBUG: Started auxiliary module DigiSig
2016-03-06 07:00:31,125 [root] DEBUG: Started auxiliary module Disguise
2016-03-06 07:00:31,125 [root] DEBUG: Started auxiliary module Human
2016-03-06 07:00:31,140 [root] DEBUG: Started auxiliary module Screenshots
2016-03-06 07:00:31,140 [root] DEBUG: Started auxiliary module Usage
2016-03-06 07:00:31,171 [lib.api.process] INFO: Successfully executed process from path "C:\DOCUME~1\JOHN~1.MCL\LOCALS~1\Temp\corebot_dump.exe" with arguments "" with pid 2000
2016-03-06 07:00:31,187 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2016-03-06 07:00:31,233 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 2000
2016-03-06 07:00:33,233 [lib.api.process] INFO: Successfully resumed process with pid 2000
2016-03-06 07:00:33,233 [root] INFO: Added new process to list with pid: 2000
2016-03-06 07:00:33,296 [root] INFO: Cuckoomon successfully loaded in process with pid 2000.
2016-03-06 07:00:33,405 [root] INFO: Announced 32-bit process name: drwtsn32.exe pid: 116
2016-03-06 07:00:33,421 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2016-03-06 07:00:33,421 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 116
2016-03-06 07:00:33,421 [root] INFO: Disabling sleep skipping.
2016-03-06 07:00:33,453 [root] INFO: Disabling sleep skipping.
2016-03-06 07:00:33,483 [root] INFO: Added new process to list with pid: 116
2016-03-06 07:00:33,483 [root] INFO: Cuckoomon successfully loaded in process with pid 116.
2016-03-06 07:00:33,500 [root] INFO: Added new file to list with path: C:\Documents and Settings\All Users\Application Data\Microsoft\Dr Watson\drwtsn32.log
2016-03-06 07:01:03,671 [root] INFO: Notified of termination of process with pid 2000.
2016-03-06 07:01:04,015 [root] INFO: Added new file to list with path: C:\Documents and Settings\All Users\Application Data\Microsoft\Dr Watson\user.dmp
2016-03-06 07:01:04,703 [root] INFO: Notified of termination of process with pid 116.
2016-03-06 07:01:05,233 [root] INFO: Process with pid 2000 has terminated
2016-03-06 07:01:06,233 [root] INFO: Process with pid 116 has terminated
2016-03-06 07:01:25,233 [root] INFO: Process list is empty, terminating analysis.
2016-03-06 07:01:26,233 [root] INFO: Created shutdown mutex.
2016-03-06 07:01:27,233 [root] INFO: Shutting down package.
2016-03-06 07:01:27,233 [root] INFO: Stopping auxiliary modules.
2016-03-06 07:01:27,233 [root] INFO: Finishing auxiliary modules.
2016-03-06 07:01:27,233 [root] INFO: Shutting down pipe server and dumping dropped files.
2016-03-06 07:01:27,280 [root] INFO: Analysis completed.
2016-03-06 07:01:27,296 [root] INFO: Testing
```

**Comment by spender-sandbox** [comment]
And to confirm, this is with the updated agent.py installed in the guest & re-snapshotted?

-Brad

**Comment by exp0se** [comment]
Yep

**Comment by doomedraven** [comment]
heh just did deploy of new version, getting the same error, will try make some tests around

**Comment by doomedraven** [comment]
@spender-sandbox one question, completion_key must be set in config no? locking for initialization of that value i see what is created empty, and tried to be got from `self.config.get(completion_key)`

**Comment by doomedraven** [comment]
ah found it, config.set("analysis", "completion_key", COMPLETION_KEY)

**Comment by exp0se** [comment]
The commit 7ef09d2026e2f782b770f8a074cc66d41d69d982 doesn't appear to be fixed the problem. 

I am still hitting a timeout and completion key is still blank before it used:
```
2016-03-12 23:49:16,000 [root] INFO: Date set to: 03-13-16, time set to: 07:49:16
2016-03-12 23:49:16,000 [root] DEBUG: Starting analyzer from: C:\rfofpepbs
2016-03-12 23:49:16,000 [root] DEBUG: Storing results at: C:\cWznoq
2016-03-12 23:49:16,000 [root] DEBUG: Pipe server name: \\.\PIPE\pPEyxZor
2016-03-12 23:49:16,000 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2016-03-12 23:49:16,000 [root] INFO: Automatically selected analysis package "exe"
2016-03-12 23:49:16,250 [root] DEBUG: Started auxiliary module Browser
2016-03-12 23:49:16,250 [modules.auxiliary.digisig] INFO: Skipping authenticode validation, signtool.exe was not found in bin/
2016-03-12 23:49:16,250 [root] DEBUG: Started auxiliary module DigiSig
2016-03-12 23:49:16,250 [root] DEBUG: Started auxiliary module Disguise
2016-03-12 23:49:16,250 [root] DEBUG: Started auxiliary module Human
2016-03-12 23:49:16,250 [root] DEBUG: Started auxiliary module Screenshots
2016-03-12 23:49:16,250 [root] DEBUG: Started auxiliary module Usage
2016-03-12 23:49:16,296 [lib.api.process] INFO: Successfully executed process from path "C:\Users\ARTUR~1.DON\AppData\Local\Temp\runrun.exe" with arguments "" with pid 1924
2016-03-12 23:49:16,296 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2016-03-12 23:49:16,405 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 1924
2016-03-12 23:49:18,405 [lib.api.process] INFO: Successfully resumed process with pid 1924
2016-03-12 23:49:18,405 [root] INFO: Added new process to list with pid: 1924
2016-03-12 23:49:18,453 [root] INFO: Cuckoomon successfully loaded in process with pid 1924.
2016-03-12 23:49:18,453 [root] INFO: Added new file to list with path: C:\Users\ar\AppData\Local\Temp\jhuhugit.temp
2016-03-12 23:51:17,437 [root] INFO: Analysis timeout hit, terminating analysis.
2016-03-12 23:51:17,437 [root] INFO: Created shutdown mutex.
2016-03-12 23:51:18,453 [root] INFO: Shutting down package.
2016-03-12 23:51:18,453 [root] INFO: Stopping auxiliary modules.
2016-03-12 23:51:18,953 [root] INFO: Finishing auxiliary modules.
2016-03-12 23:51:18,953 [root] INFO: Shutting down pipe server and dumping dropped files.
2016-03-12 23:51:19,015 [root] INFO: Analysis completed.
2016-03-12 23:51:19,015 [root] INFO: Completion key: 
```

**Comment by spender-sandbox** [comment]
Can you add some code to just read and print out the entire contents of the analysis.conf where that completion key printout is?

-Brad

**Comment by exp0se** [comment]
Not sure how to do this.
I've added the following code, hopefully this is what you've asked:
```python
        server = xmlrpclib.Server("http://127.0.0.1:8000")
        log.info("Config: %s" % analyzer.config.get_options())
        log.info("Completion key: %s" % completion_key)
        server.complete(success, error, completion_key)

```

```
2016-03-14 00:15:51,000 [root] INFO: Date set to: 03-14-16, time set to: 08:15:51
2016-03-14 00:15:51,015 [root] DEBUG: Starting analyzer from: C:\nspkhdzab
2016-03-14 00:15:51,015 [root] DEBUG: Storing results at: C:\ZzGYQdz
2016-03-14 00:15:51,015 [root] DEBUG: Pipe server name: \\.\PIPE\wwrTcwBzj
2016-03-14 00:15:51,015 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2016-03-14 00:15:51,015 [root] INFO: Automatically selected analysis package "exe"
2016-03-14 00:15:51,125 [root] DEBUG: Started auxiliary module Browser
2016-03-14 00:15:51,125 [modules.auxiliary.digisig] INFO: Skipping authenticode validation, signtool.exe was not found in bin/
2016-03-14 00:15:51,125 [root] DEBUG: Started auxiliary module DigiSig
2016-03-14 00:15:51,140 [root] WARNING: Cannot execute auxiliary module Disguise: global name 'random_string' is not defined
2016-03-14 00:15:51,140 [root] DEBUG: Started auxiliary module Human
2016-03-14 00:15:51,140 [root] DEBUG: Started auxiliary module Screenshots
2016-03-14 00:15:51,140 [root] DEBUG: Started auxiliary module Usage
2016-03-14 00:15:51,171 [lib.api.process] INFO: Successfully executed process from path "C:\DOCUME~1\JOHN~1.MCL\LOCALS~1\Temp\runrun.exe" with arguments "" with pid 2004
2016-03-14 00:15:51,203 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2016-03-14 00:15:51,217 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 2004
2016-03-14 00:15:53,217 [lib.api.process] INFO: Successfully resumed process with pid 2004
2016-03-14 00:15:53,217 [root] INFO: Added new process to list with pid: 2004
2016-03-14 00:15:53,250 [root] INFO: Cuckoomon successfully loaded in process with pid 2004.
2016-03-14 00:15:53,265 [root] INFO: Added new file to list with path: C:\Documents and Settings\john.mclaren\Local Settings\Temp\jhuhugit.temp
2016-03-14 00:17:52,280 [root] INFO: Analysis timeout hit, terminating analysis.
2016-03-14 00:17:52,296 [root] INFO: Created shutdown mutex.
2016-03-14 00:17:53,296 [root] INFO: Shutting down package.
2016-03-14 00:17:53,312 [root] INFO: Stopping auxiliary modules.
2016-03-14 00:17:53,812 [root] INFO: Finishing auxiliary modules.
2016-03-14 00:17:53,812 [root] INFO: Shutting down pipe server and dumping dropped files.
2016-03-14 00:17:53,921 [root] INFO: Analysis completed.
2016-03-14 00:17:53,921 [root] INFO: Config: {}
2016-03-14 00:17:53,921 [root] INFO: Completion key: 
```

**Comment by spender-sandbox** [comment]
Ah, no sorry could you add the code here:
https://github.com/spender-sandbox/cuckoo-modified/blob/c4155c03f125c2685c3e4139c7bd9b5ff6a069ca/analyzer/windows/analyzer.py#L795

and make it:
print os.open("analysis.conf", "rb").read()

Thanks,
-Brad

**Comment by exp0se** [comment]
Done, but got a traceback:
```
2016-06-22 12:03:23,015 [root] ERROR: Traceback (most recent call last):
  File "C:\wxhbbluj\analyzer.py", line 1149, in <module>
    success = analyzer.run()
  File "C:\wxhbbluj\analyzer.py", line 879, in run
    self.prepare()
  File "C:\wxhbbluj\analyzer.py", line 792, in prepare
    print os.open("analysis.conf", "rb").read()
TypeError: an integer is required
Traceback (most recent call last):
  File "C:\wxhbbluj\analyzer.py", line 1149, in <module>
    success = analyzer.run()
  File "C:\wxhbbluj\analyzer.py", line 879, in run
    self.prepare()
  File "C:\wxhbbluj\analyzer.py", line 792, in prepare
    print os.open("analysis.conf", "rb").read()
TypeError: an integer is required
2016-06-22 12:03:23,015 [root] INFO: Config: {}
2016-06-22 12:03:23,015 [root] INFO: Completion key: 
```

**Comment by spender-sandbox** [comment]
Sorry, open instead of os.open

-Brad

**Comment by exp0se** [comment]
No problem, seems blank though:
```
2016-03-14 03:23:33,000 [root] INFO: Date set to: 03-14-16, time set to: 11:23:33
2016-03-14 03:23:33,000 [root] DEBUG: Starting analyzer from: C:\wxhbbluj
2016-03-14 03:23:33,015 [root] DEBUG: Storing results at: C:\PforGALXbJ
2016-03-14 03:23:33,015 [root] DEBUG: Pipe server name: \\.\PIPE\GqHeYDHmd
2016-03-14 03:23:33,015 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2016-03-14 03:23:33,015 [root] INFO: Automatically selected analysis package "exe"
2016-03-14 03:23:33,125 [root] DEBUG: Started auxiliary module Browser
2016-03-14 03:23:33,125 [modules.auxiliary.digisig] INFO: Skipping authenticode validation, signtool.exe was not found in bin/
2016-03-14 03:23:33,125 [root] DEBUG: Started auxiliary module DigiSig
2016-03-14 03:23:33,125 [root] WARNING: Cannot execute auxiliary module Disguise: global name 'random_string' is not defined
2016-03-14 03:23:33,125 [root] DEBUG: Started auxiliary module Human
2016-03-14 03:23:33,125 [root] DEBUG: Started auxiliary module Screenshots
2016-03-14 03:23:33,125 [root] DEBUG: Started auxiliary module Usage
2016-03-14 03:23:33,171 [lib.api.process] INFO: Successfully executed process from path "C:\DOCUME~1\JOHN~1.MCL\LOCALS~1\Temp\runrun.exe" with arguments "" with pid 2000
2016-03-14 03:23:33,187 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2016-03-14 03:23:33,233 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 2000
2016-03-14 03:23:35,233 [lib.api.process] INFO: Successfully resumed process with pid 2000
2016-03-14 03:23:35,233 [root] INFO: Added new process to list with pid: 2000
2016-03-14 03:23:35,265 [root] INFO: Cuckoomon successfully loaded in process with pid 2000.
2016-03-14 03:23:35,280 [root] INFO: Added new file to list with path: C:\Documents and Settings\john.mclaren\Local Settings\Temp\jhuhugit.temp
2016-03-14 03:25:34,265 [root] INFO: Analysis timeout hit, terminating analysis.
2016-03-14 03:25:34,265 [root] INFO: Created shutdown mutex.
2016-03-14 03:25:35,265 [root] INFO: Shutting down package.
2016-03-14 03:25:35,265 [root] INFO: Stopping auxiliary modules.
2016-03-14 03:25:35,765 [root] INFO: Finishing auxiliary modules.
2016-03-14 03:25:35,780 [root] INFO: Shutting down pipe server and dumping dropped files.
2016-03-14 03:25:35,905 [root] INFO: Analysis completed.
2016-03-14 03:25:35,905 [root] INFO: Completion key: 
```

**Comment by spender-sandbox** [comment]
Ah whoops, sorry, should have said to do log.info() instead of print :)

-Brad

**Comment by exp0se** [comment]
Here you go:

```
2016-06-22 12:03:23,015 [root] INFO: [analysis]
category = file
exports = 
target = /tmp/cuckoo-tmp/upload_wv33CN/runrun.exe
package = 
terminate_processes = False
ip = 192.168.56.1
clock = 20160314T11:42:52
options = 
file_type = PE32 executable (GUI) Intel 80386, for MS Windows
enforce_timeout = False
timeout = 120
file_name = 'runrun.exe'
id = 64
port = 2042
completion_key = qrnjcjkdhtxjcssczy


2016-03-14 03:42:52,000 [root] INFO: Date set to: 03-14-16, time set to: 11:42:52
2016-03-14 03:42:52,015 [root] DEBUG: Starting analyzer from: C:\mbyagius
2016-03-14 03:42:52,015 [root] DEBUG: Storing results at: C:\jcXnIq
2016-03-14 03:42:52,015 [root] DEBUG: Pipe server name: \\.\PIPE\oBLHQsUiZ
2016-03-14 03:42:52,015 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2016-03-14 03:42:52,015 [root] INFO: Automatically selected analysis package "exe"
2016-03-14 03:42:52,125 [root] DEBUG: Started auxiliary module Browser
2016-03-14 03:42:52,125 [modules.auxiliary.digisig] INFO: Skipping authenticode validation, signtool.exe was not found in bin/
2016-03-14 03:42:52,125 [root] DEBUG: Started auxiliary module DigiSig
2016-03-14 03:42:52,125 [root] WARNING: Cannot execute auxiliary module Disguise: global name 'random_string' is not defined
2016-03-14 03:42:52,125 [root] DEBUG: Started auxiliary module Human
2016-03-14 03:42:52,140 [root] DEBUG: Started auxiliary module Screenshots
2016-03-14 03:42:52,140 [root] DEBUG: Started auxiliary module Usage
2016-03-14 03:42:52,155 [lib.api.process] INFO: Successfully executed process from path "C:\DOCUME~1\JOHN~1.MCL\LOCALS~1\Temp\runrun.exe" with arguments "" with pid 1992
2016-03-14 03:42:52,171 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2016-03-14 03:42:52,203 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 1992
2016-03-14 03:42:54,203 [lib.api.process] INFO: Successfully resumed process with pid 1992
2016-03-14 03:42:54,203 [root] INFO: Added new process to list with pid: 1992
2016-03-14 03:42:54,265 [root] INFO: Cuckoomon successfully loaded in process with pid 1992.
2016-03-14 03:42:54,280 [root] INFO: Added new file to list with path: C:\Documents and Settings\john.mclaren\Local Settings\Temp\jhuhugit.temp
2016-03-14 03:44:53,217 [root] INFO: Analysis timeout hit, terminating analysis.
2016-03-14 03:44:53,217 [root] INFO: Created shutdown mutex.
2016-03-14 03:44:54,217 [root] INFO: Shutting down package.
2016-03-14 03:44:54,217 [root] INFO: Stopping auxiliary modules.
2016-03-14 03:44:54,717 [root] INFO: Finishing auxiliary modules.
2016-03-14 03:44:54,717 [root] INFO: Shutting down pipe server and dumping dropped files.
2016-03-14 03:44:54,796 [root] INFO: Analysis completed.
2016-03-14 03:44:54,812 [root] INFO: Completion key: 
```

**Comment by spender-sandbox** [comment]
And if you do a:
log.info(self.config.get_options().get("completion_key"))

right under that line, does it print the key?

-Brad

**Comment by exp0se** [comment]
Still blank:
```
2016-06-22 12:03:23,000 [root] INFO: [analysis]
category = file
exports = 
target = /tmp/cuckoo-tmp/upload_CCTegw/runrun.exe
package = 
terminate_processes = False
ip = 192.168.56.1
clock = 20160314T13:16:47
options = 
file_type = PE32 executable (GUI) Intel 80386, for MS Windows
enforce_timeout = False
timeout = 120
file_name = 'runrun.exe'
id = 65
port = 2042
completion_key = skjcgakgqiqskhamm


2016-06-22 12:03:23,000 [root] INFO: None
2016-03-14 05:16:47,000 [root] INFO: Date set to: 03-14-16, time set to: 13:16:47
2016-03-14 05:16:47,015 [root] DEBUG: Starting analyzer from: C:\wxhbbluj
2016-03-14 05:16:47,015 [root] DEBUG: Storing results at: C:\JogRNJbIMu
2016-03-14 05:16:47,015 [root] DEBUG: Pipe server name: \\.\PIPE\DptYGqUx
2016-03-14 05:16:47,015 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2016-03-14 05:16:47,015 [root] INFO: Automatically selected analysis package "exe"
2016-03-14 05:16:47,125 [root] DEBUG: Started auxiliary module Browser
2016-03-14 05:16:47,125 [modules.auxiliary.digisig] INFO: Skipping authenticode validation, signtool.exe was not found in bin/
2016-03-14 05:16:47,125 [root] DEBUG: Started auxiliary module DigiSig
2016-03-14 05:16:47,125 [root] WARNING: Cannot execute auxiliary module Disguise: global name 'random_string' is not defined
2016-03-14 05:16:47,125 [root] DEBUG: Started auxiliary module Human
2016-03-14 05:16:47,125 [root] DEBUG: Started auxiliary module Screenshots
2016-03-14 05:16:47,140 [root] DEBUG: Started auxiliary module Usage
2016-03-14 05:16:47,171 [lib.api.process] INFO: Successfully executed process from path "C:\DOCUME~1\JOHN~1.MCL\LOCALS~1\Temp\runrun.exe" with arguments "" with pid 2004
2016-03-14 05:16:47,187 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2016-03-14 05:16:47,233 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 2004
2016-03-14 05:16:49,233 [lib.api.process] INFO: Successfully resumed process with pid 2004
2016-03-14 05:16:49,233 [root] INFO: Added new process to list with pid: 2004
2016-03-14 05:16:49,280 [root] INFO: Cuckoomon successfully loaded in process with pid 2004.
2016-03-14 05:16:49,280 [root] INFO: Added new file to list with path: C:\Documents and Settings\john.mclaren\Local Settings\Temp\jhuhugit.temp
2016-03-14 05:18:48,250 [root] INFO: Analysis timeout hit, terminating analysis.
2016-03-14 05:18:48,250 [root] INFO: Created shutdown mutex.
2016-03-14 05:18:49,250 [root] INFO: Shutting down package.
2016-03-14 05:18:49,250 [root] INFO: Stopping auxiliary modules.
2016-03-14 05:18:49,750 [root] INFO: Finishing auxiliary modules.
2016-03-14 05:18:49,765 [root] INFO: Shutting down pipe server and dumping dropped files.
2016-03-14 05:18:49,875 [root] INFO: Analysis completed.
2016-03-14 05:18:49,875 [root] INFO: Completion key: 
```

**Comment by spender-sandbox** [comment]
Should be fixed now, thanks!

-Brad

**Comment by exp0se** [comment]
Yay! Now its fixed.

Thanks for taking a time to fix this issue!
