### ISSUE TITLE
django.conf.urls.patterns removed in django 1.10

### ISSUE THREAD

**Issue by lehuff** [spender-sandbox/cuckoo-modified#242]
django.conf.urls.patterns() is removed per django release notes: https://docs.djangoproject.com/en/1.10/releases/1.10/

error message follows:

[cuckoo@cuckoo-cent web]$ Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x341a668>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/cuckoo-modified/web/web/urls.py", line 5, in <module>
    from django.conf.urls import patterns, include, url
ImportError: cannot import name patterns

**Comment by muhviehstah** [comment]
cherry picked your commit but still get an error when access the analysis  ("recents") view.

 someone has tested django 1.10 already?

**Comment by doomedraven** [comment]
@muhviehstah try update now and check it, now should be solved

**Comment by NilanjPatel** [comment]
any other options?

**Comment by lehuff** [comment]
Use 1.9.9. Works perfectly eve with the newer versions.

**Comment by marek2003** [comment]
I agree pip  install django==1.9.9

**Comment by NilanjPatel** [comment]
thanks @lehuff @marek2003  it works

**Comment by KillerInstinct** [comment]
Why exactly does 1.10 not work? The issue for this was already resolved.

**Comment by lehuff** [comment]
It does work now, assuming he updated his code.

**Comment by eve1234** [comment]
Where is the code and where do I update it?
