### ISSUE TITLE
cannot import name caches

### ISSUE THREAD

**Issue by fulco** [spender-sandbox/cuckoo-modified#248]
I just went through an upgrade and patch day.  Now I'm getting this error on the Web Interface.  I'm certain it's something I updated that I shouldn't, or some other detail I missed.  Any guidance on the fix would be appreciated.  I have searched and can't seem to find any relevant help.

Thanks for your time folks.

```
ImportError at /

cannot import name caches

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/
Django Version: 	1.6.1
Exception Type: 	ImportError
Exception Value: 	

cannot import name caches

Exception Location: 	/usr/local/lib/python2.7/dist-packages/ratelimit/utils.py in <module>, line 8
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6
Python Path: 	

['/home/user/Downloads/cuckoo-modified-master/web',
 '/usr/local/lib/python2.7/dist-packages/volatility-2.4-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/mastiff-0.6.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/Yapsy-1.11.023-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/setuptools-1.3.2-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/cybox-2.1.0.12-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/stix-1.1.1.4-py2.7.egg',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/home/user/Downloads/cuckoo-modified-master/web/..',
 '/home/user/Downloads/cuckoo-modified-master',
 '/home/user/Downloads/cuckoo-modified-master/web',
 '/home/user/Downloads/cuckoo-modified-master/web/..',
 '/home/user/Downloads/cuckoo-modified-master/web/..',
 '/home/user/Downloads/cuckoo-modified-master/web/..',
 '/home/user/Downloads/cuckoo-modified-master/web/..',
 '/home/user/Downloads/cuckoo-modified-master/web/..']

Server time: 	Mon, 15 Aug 2016 11:45:37 -0500
```

Edit:
I also am getting this when trying a manual submission. 

```
user@ren:~/Downloads/cuckoo-modified/utils$ ./submit.py ~/Documents/MAL/20150405-AOC1/po.exe 
Traceback (most recent call last):
  File "./submit.py", line 278, in <module>
    main()
  File "./submit.py", line 72, in main
    db = Database()
  File "/home/user/Downloads/cucknew/20160811/cuckoo-modified/utils/../lib/cuckoo/common/utils.py", line 1511, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/user/Downloads/cucknew/20160811/cuckoo-modified/utils/../lib/cuckoo/core/database.py", line 412, in __init__
    SCHEMA_VERSION))
lib.cuckoo.common.exceptions.CuckooDatabaseError: DB schema version mismatch: found 3c8bf4133b44, expected 4b09c454108c. Try to apply all migrations (cd utils/db_migration/ && alembic upgrade head).
user@ren:~/Downloads/cuckoo-modified/utils$ ^C
user@ren:~/Downloads/cuckoo-modified/utils$ cd db_migration/ && alembic upgrade head
INFO  [alembic.migration] Context impl MySQLImpl.
INFO  [alembic.migration] Will assume non-transactional DDL.
  No such revision '3c8bf4133b44'

```

I've dropped databases completely and tried a clean install of Cuckoo.  I reran the requirements.txt install sequence.  Still getting the same errors.  Makes me thinks it's definitely related to some package  change I did.  Any guidance back on track is appreciated.

Thanks!

**Comment by KillerInstinct** [comment]
I believe this is due to installing ratelimit and not django-ratelimit -- could you confirm?

**Comment by fulco** [comment]
I have verified that the package installed is django-ratelimit and not ratelimit.  At least that's all that's in my python directory.

`Downloading/unpacking django-ratelimit (from -r requirements.txt (line 7))
  Downloading django_ratelimit-1.0.0-py2.py3-none-any.whl
`

http://dpaste.com/2FF94XA

**Comment by KillerInstinct** [comment]
For the Django import error, upgrade to any versions between 1.7 and 1.9 and give it a try. 1.10 should work too, but I've not tested it.

**Comment by fulco** [comment]
Got Django 1.9 installed and it now appears to be working.  Thanks for the pointers.
