### ISSUE TITLE
Retention module errorring out

### ISSUE THREAD

**Issue by lehuff** [spender-sandbox/cuckoo-modified#250]
Every time the retetion module runs I get the following error in the process.log:

2016-08-16 12:16:14,749 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "Retention":
Traceback (most recent call last):
  File "/opt/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 629, in process
    current.run(self.results)
  File "/opt/cuckoo-modified/utils/../modules/reporting/retention.py", line 204, in run
    delete_mongo_data(curtask, lastTask)
  File "/opt/cuckoo-modified/utils/../modules/reporting/retention.py", line 59, in delete_mongo_data
    results_db.calls.remove({"_id": ObjectId(call)})
NameError: global name 'ObjectId' is not defined

Here are my settings in reporting.conf (intentionally set low):

[retention]
enabled = yes
# run at most once every this many hours (unless reporting.conf is modified)
run_every = 6
# The amount of days old a task needs to be before deleting data
# Set a value to no to never delete it
memory = 5
procmemory = 5
pcap = 5
sortedpcap = 5
bsonlogs = 5
dropped = 5
screencaps = 5
reports = 5
mongo = 5
elastic = no
malheur = no

**Comment by spender-sandbox** [comment]
Should be fixed now, thanks

-Brad

**Comment by lehuff** [comment]
Confirmed fixed.  Thank you!
-Lane
