### ISSUE TITLE
The analysis hit the critical timeout, terminating

### ISSUE THREAD

**Issue by HelioCD** [spender-sandbox/cuckoo-modified#255]
Hello,
I've just installed the new master package of cuckoo-modified on Ubuntu 16.04. I got it to work at one point but for some reason it doesn't work anymore.
- Firewall & UAC turned off of Win7x64 guest.
- Guest & host are communicating via Host-only connection.
- Guest can get to the Internet with port forwarding on host.
- Newest agent.py is in startup in guest.

Below is the debug level log, please let me know what other logs you need or what I'm missing. Thanks!

2016-08-22 17:52:08,605 [lib.cuckoo.core.resultserver] DEBUG: ResultServer running on 192.168.56.1:2042.
2016-08-22 17:52:08,607 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" machine manager with max_analysis_count=0, max_machines_count=0, and max_vmstartup_count=10
2016-08-22 17:52:08,727 [modules.machinery.virtualbox] DEBUG: Getting status for Win7x64
2016-08-22 17:52:08,857 [modules.machinery.virtualbox] DEBUG: Machine Win7x64 status poweroff
2016-08-22 17:52:08,940 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-08-22 17:52:08,984 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-08-22 17:52:41,933 [lib.cuckoo.core.scheduler] DEBUG: Task #2: Processing task
2016-08-22 17:52:41,935 [lib.cuckoo.core.scheduler] INFO: Task #2: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_kPw3_5/International Operations - LAR Org Chart.pdf'
2016-08-22 17:52:41,960 [lib.cuckoo.core.scheduler] INFO: Task #2: acquired machine Win7x64 (label=Win7x64)
2016-08-22 17:52:41,982 [modules.machinery.virtualbox] DEBUG: Starting vm Win7x64
2016-08-22 17:52:41,982 [modules.machinery.virtualbox] DEBUG: Getting status for Win7x64
2016-08-22 17:52:42,093 [modules.machinery.virtualbox] DEBUG: Machine Win7x64 status poweroff
2016-08-22 17:52:42,157 [modules.machinery.virtualbox] DEBUG: Using current snapshot for virtual machine Win7x64
2016-08-22 17:52:42,262 [modules.machinery.virtualbox] DEBUG: Getting status for Win7x64
2016-08-22 17:52:42,419 [modules.machinery.virtualbox] DEBUG: Machine Win7x64 status saved
2016-08-22 17:52:47,239 [modules.machinery.virtualbox] DEBUG: Getting status for Win7x64
2016-08-22 17:52:47,521 [modules.machinery.virtualbox] DEBUG: Machine Win7x64 status running
2016-08-22 17:52:47,618 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 11334 (interface=vboxnet0, host=192.168.56.101, dump path=/opt/cuckoo-modified/storage/analyses/2/dump.pcap)
2016-08-22 17:52:47,620 [lib.cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2016-08-22 17:52:47,620 [lib.cuckoo.core.plugins] DEBUG: Started auxiliary module: Tor
2016-08-22 17:52:47,623 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=Win7x64, ip=192.168.56.101)
2016-08-22 17:52:47,631 [lib.cuckoo.core.guest] DEBUG: Win7x64: waiting for status 0x0001
2016-08-22 17:52:54,659 [lib.cuckoo.core.guest] DEBUG: Win7x64: status ready
2016-08-22 17:52:54,693 [lib.cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=Win7x64, ip=192.168.56.101)
2016-08-22 17:52:55,120 [lib.cuckoo.core.guest] DEBUG: Win7x64: analyzer started with PID 3048
2016-08-22 17:52:55,120 [lib.cuckoo.core.guest] DEBUG: Win7x64: waiting for completion
2016-08-22 17:52:56,123 [lib.cuckoo.core.guest] DEBUG: Win7x64: analysis not completed yet (status=2)
2016-08-22 17:52:57,128 [lib.cuckoo.core.guest] DEBUG: Win7x64: analysis not completed yet (status=2)
2016-08-22 17:52:58,150 [lib.cuckoo.core.guest] DEBUG: Win7x64: analysis not completed yet (status=2)
2016-08-22 17:52:59,166 [lib.cuckoo.core.guest] DEBUG: Win7x64: analysis not completed yet (status=2)
...
2016-08-22 17:40:15,793 [lib.cuckoo.core.guest] DEBUG: Win7x64: analysis not completed yet (status=2)
2016-08-22 17:40:16,795 [lib.cuckoo.core.scheduler] ERROR: **The analysis hit the critical timeout, terminating**.
2016-08-22 17:40:16,815 [lib.cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Sniffer
2016-08-22 17:40:16,815 [lib.cuckoo.core.plugins] DEBUG: Stopped auxiliary module: Tor
2016-08-22 17:40:16,816 [modules.machinery.virtualbox] DEBUG: Stopping vm Win7x64
2016-08-22 17:40:16,819 [modules.machinery.virtualbox] DEBUG: Getting status for Win7x64
2016-08-22 17:40:16,942 [modules.machinery.virtualbox] DEBUG: Machine Win7x64 status running
2016-08-22 17:40:17,968 [modules.machinery.virtualbox] DEBUG: Getting status for Win7x64
2016-08-22 17:40:18,220 [modules.machinery.virtualbox] DEBUG: Machine Win7x64 status poweroff
2016-08-22 17:40:18,334 [lib.cuckoo.core.scheduler] DEBUG: Task #2: Released database task with status False
2016-08-22 17:40:18,337 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "Decompression" on analysis at "/opt/cuckoo-modified/storage/analyses/2"
2016-08-22 17:40:18,338 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "AnalysisInfo" on analysis at "/opt/cuckoo-modified/storage/analyses/2"
2016-08-22 17:40:18,358 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "BehaviorAnalysis" on analysis at "/opt/cuckoo-modified/storage/analyses/2"
2016-08-22 17:40:18,359 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path "/opt/cuckoo-modified/storage/analyses/2/logs".
2016-08-22 17:40:18,360 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "Debug" on analysis at "/opt/cuckoo-modified/storage/analyses/2"
2016-08-22 17:40:18,367 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "Dropped" on analysis at "/opt/cuckoo-modified/storage/analyses/2"
2016-08-22 17:40:18,369 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Dropped":
Traceback (most recent call last):
  File "/opt/cuckoo-modified/lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/opt/cuckoo-modified/modules/processing/dropped.py", line 26, in run
    file_names = os.listdir(self.dropped_path)
OSError: [Errno 2] No such file or directory: '/opt/cuckoo-modified/storage/analyses/2/files'
2016-08-22 17:40:18,370 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "NetworkAnalysis" on analysis at "/opt/cuckoo-modified/storage/analyses/2"
2016-08-22 17:40:18,497 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "Static" on analysis at "/opt/cuckoo-modified/storage/analyses/2"
2016-08-22 17:40:18,498 [modules.processing.static] DEBUG: Starting to load PDF
2016-08-22 17:40:18,616 [modules.processing.static] DEBUG: About to parse with PDFParser
2016-08-22 17:40:18,664 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "Strings" on analysis at "/opt/cuckoo-modified/storage/analyses/2"
2016-08-22 17:40:18,667 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "TargetInfo" on analysis at "/opt/cuckoo-modified/storage/analyses/2"
2016-08-22 17:40:18,668 [lib.cuckoo.common.objects] WARNING: Unable to import yara (please compile from sources)
2016-08-22 17:40:18,668 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "VirusTotal" on analysis at "/opt/cuckoo-modified/storage/analyses/2"

**Comment by lehuff** [comment]
are you still getting results? I have a number of samples that pretty much always hit the timeout

**Comment by HelioCD** [comment]
Yes I still get results, just not complete ones. The result basically has a bit of static analysis and AV, other analysis are empty.
I get this with all kind of files, have been trying with many samples now with same results.

Any suggestion would be appreciated.

Thanks,

**Comment by spender-sandbox** [comment]
Generally this means your guest VM has trouble connecting to the resultserver (port 2042) on the host.  Make sure your firewall rules are allowing this.

-Brad

**Comment by HelioCD** [comment]
Thanks Brad. I turned off firewall on Ubuntu 16.04 host and got the full analysis now, so looks like guest is able to connect to host on port 2042 fine now. But I still get the "The analysis hit the critical timeout" error. Tried increasing "critical timeout" in cuckoo.conf file as well and it didn't help.

I installed cuckoo-modified in another host, Ubuntu 14, everything is the same, firewall off, and did not get the error, didn't need to change timeout time. Analysis on the same sample, Ubuntu 14 is much faster, even with less resources, Ubuntu 16 gets all analysis done but still says "analysis not completed yet (status=2)" then hit "critical timeout" error.

Any idea/suggestion? Any incompatibility with Ubuntu 16? If not, I'd most likely go with Ubuntu 14 to save the hassle.

Thanks all,

**Comment by spender-sandbox** [comment]
Do you get any analysis.log or behavioral results from the ubuntu 16 machine?  And the guests are exact copies of each other?

-Brad

**Comment by jgajek** [comment]
I am also running on Ubuntu 16.04  and occasionally get the critical timeouts.  When this happens, there are debug messages in the Cuckoo log:

2016-08-24 14:55:10,690 [lib.cuckoo.core.guest] DEBUG: win_vm: error retrieving status: [Errno 110] Connection timed out
2016-08-24 14:57:18,946 [lib.cuckoo.core.guest] DEBUG: win_vm: error retrieving status: [Errno 110] Connection timed out
2016-08-24 14:59:27,202 [lib.cuckoo.core.guest] DEBUG: win_vm: error retrieving status: [Errno 110] Connection timed out

The analysis still completes successfully, it just takes longer because Cuckoo can't retrieve the current status from the agent.  I am still trying to track down the root cause.

**Comment by HelioCD** [comment]
Below is the analysis.log file my latest completed analysis on an executable file with that "critical timeout" error. Couldn't see any obvious issue. Yes the guests are exact copies.
Thanks for your help!
-----------------------------
2016-04-25 19:28:33,000 [root] INFO: Date set to: 04-26-16, time set to: 01:28:3
3
2016-04-25 19:28:33,015 [root] DEBUG: Starting analyzer from: C:\kfsyiy
2016-04-25 19:28:33,015 [root] DEBUG: Storing results at: C:\krpILsAiG
2016-04-25 19:28:33,030 [root] DEBUG: Pipe server name: \\.\PIPE\PHMoSbo
2016-04-25 19:28:33,030 [root] DEBUG: No analysis package specified, trying to d
etect it automagically.
2016-04-25 19:28:33,030 [root] INFO: Automatically selected analysis package "ex
e"
2016-04-25 19:28:33,171 [root] DEBUG: Started auxiliary module Browser
2016-04-25 19:28:33,187 [modules.auxiliary.digisig] INFO: Skipping authenticode 
validation, signtool.exe was not found in bin/
2016-04-25 19:28:33,187 [root] DEBUG: Started auxiliary module DigiSig
2016-04-25 19:28:33,187 [root] DEBUG: Started auxiliary module Disguise
2016-04-25 19:28:33,187 [root] DEBUG: Started auxiliary module Human
2016-04-25 19:28:33,187 [root] DEBUG: Started auxiliary module Screenshots
2016-04-25 19:28:33,187 [root] DEBUG: Started auxiliary module Usage
2016-04-25 19:28:33,217 [lib.api.process] INFO: Successfully executed process fr
om path "C:\Users\admin\AppData\Local\Temp\f.exe" with arguments "" with pid 246
8
2016-04-25 19:28:33,233 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2016-04-25 19:28:33,280 [lib.api.process] INFO: Injected into suspended 32-bit p
rocess with pid 2468
2016-04-25 19:28:35,280 [lib.api.process] INFO: Successfully resumed process with pid 2468
2016-04-25 19:28:35,280 [root] INFO: Added new process to list with pid: 2468
2016-04-25 19:28:35,467 [root] INFO: Cuckoomon successfully loaded in process with pid 2468.
2016-04-25 19:28:35,500 [root] INFO: Added new file to list with path: C:\Users\admin\AppData\Local\Temp\taskhost.exe
2016-04-25 19:28:35,733 [root] INFO: Added new file to list with path: C:\Users\admin\AppData\Local\Temp\status2.z
2016-08-23 19:28:54,997 [root] INFO: Disabling sleep skipping.
2016-08-23 19:28:56,325 [root] INFO: Notified of termination of process with pid 2468.
2016-08-23 19:28:57,154 [root] INFO: Process with pid 2468 has terminated
2016-08-23 19:29:02,200 [root] INFO: Process list is empty, terminating analysis.
2016-08-23 19:29:03,217 [root] INFO: Created shutdown mutex.
2016-08-23 19:29:04,232 [root] INFO: Shutting down package.
2016-08-23 19:29:04,232 [root] INFO: Stopping auxiliary modules.
2016-08-23 19:29:04,232 [root] INFO: Finishing auxiliary modules.
2016-08-23 19:29:04,232 [root] INFO: Shutting down pipe server and dumping dropped files.
2016-08-23 19:29:04,295 [root] INFO: Analysis completed.

**Comment by d0lph1n98** [comment]
Here take a look here: https://github.com/cuckoosandbox/cuckoo/issues/704

**Comment by MirrorFeng** [comment]
i am new to cuckoo, i submit some exe file to cuckoo,and there is no dynamic analysis, there is no analysis.log, analysis.conf and logs created by cuckoo, the web just show some static analysis result, the nohup.out file show an error:
2017-04-01 15:38:50,648 [lib.cuckoo.core.scheduler] INFO: Task #11: acquired machine guest2 (label=guest2)
2017-04-01 15:38:50,677 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 3569 (interface=vboxnet0, host=192.168.56.103, pcap=/usr/cuckoo-2.0-rc1/storage/analyses/11/dump.pcap)
dropped privs to root
tcpdump: listening on vboxnet0, link-type EN10MB (Ethernet), capture size 262144 bytes
2017-04-01 15:38:56,908 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=guest2, ip=192.168.56.103)
2017-04-01 15:49:06,960 [lib.cuckoo.core.scheduler] ERROR: The analysis hit the critical timeout, terminating.
372 packets captured
372 packets received by filter
0 packets dropped by kernel
2017-04-01 15:49:10,000 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path '/usr/cuckoo-2.0-rc1/storage/analyses/11/logs'.
2017-04-01 15:49:18,031 [lib.cuckoo.core.scheduler] INFO: Task #11: reports generation completed (path=/usr/cuckoo-2.0-rc1/storage/analyses/11)
2017-04-01 15:49:18,245 [lib.cuckoo.core.scheduler] INFO: Task #11: analysis procedure completed
i search some ways to solve this problem, like close UAC, make sure the guest can connect to host, but still have this error, i don't know what to do next

**Comment by spender-sandbox** [comment]
You created your VM snapshot with agent.py running in the guest, right?

-Brad

**Comment by MirrorFeng** [comment]
yes, agent.py is running when i create the snapshot, i use virsualbox  rather than VMware

**Comment by lehuff** [comment]
Is the windows firewall off?

**Comment by MirrorFeng** [comment]
firewall , system update and UAC  all shutdown, cuckoo just have some static analysis

**Comment by lehuff** [comment]
Try turning your host firewall off too. Assuming you can ping the system
when it's powered on?

**Comment by MirrorFeng** [comment]
my guest ip:192.168.56.103; my host ip: vboxnet0 is 192.168.56.1, eth0 is 192.168.1.220; in the guest meachine i can ping 192.168.56.1 and 192.168.1.220 and www.baidu.com

**Comment by doomedraven** [comment]
what about `curl 192.168.56.103:8000` should give you 501 error, means works fine

**Comment by jeandez** [comment]
Good afternoon, 
I am facing the same problem for a while.
curl 192.168.56.101 gives me 501 error
ping work in the both direction
i finally configured automatic logon on the guest operating system (windows 7 64 bit)
RPC service start automatically 
I do not understand what is going wrong.

----
2017-04-20 16:45:57,174 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-04-20 16:45:58,756 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-04-20 16:45:58,766 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-04-20 16:45:59,845 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "cryptowall.bin" (task #7, options "route=none,procmemdump=yes")
2017-04-20 16:45:59,867 [lib.cuckoo.core.scheduler] INFO: File already exists at "/opt/cuckoo/storage/binaries/45317968759d3e37282ceb75149f627d648534c5b4685f6da3966d8f6fca662d"
2017-04-20 16:45:59,902 [lib.cuckoo.core.scheduler] INFO: Task #7: acquired machine cuckoo1 (label=sandbox)
2017-04-20 16:45:59,916 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 3518 (interface=vboxnet0, host=192.168.56.101, pcap=/opt/cuckoo/storage/analyses/7/dump.pcap)
2017-04-20 16:46:04,960 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2017-04-20 16:51:12,098 [lib.cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.
2017-04-20 16:51:20,380 [modules.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label sandbox to path /opt/cuckoo/storage/analyses/7/memory.dmp
2017-04-20 16:51:22,232 [modules.processing.behavior] WARNING: Analysis results folder does not contain any behavior log files.
2017-04-20 16:51:24,989 [volatility.debug] WARNING: NoneObject as string: Cannot find process session
2017-04-20 16:51:24,992 [volatility.debug] WARNING: NoneObject as string: Cannot find process session
[x64] Gathering all referenced SSDTs from KeAddSystemServiceTable...

**Comment by jeandez** [comment]
I am using cuckoo 2-0.rc2

**Comment by spender-sandbox** [comment]
Wrong repo

-Brad

**Comment by jeandez** [comment]
which one should use ?

**Comment by jeandez** [comment]
apparently 2.0-rc2 is the latest.

Cuckoo Sandbox 2.0-rc2
 www.cuckoosandbox.org
 Copyright (c) 2010-2015

 Checking for updates...
 Good! You have the latest version available.

/usr/local/lib/python2.7/dist-packages/pymisp/api.py:20: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
/usr/local/lib/python2.7/dist-packages/pymisp/mispevent.py:45: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
/usr/local/lib/python2.7/dist-packages/pymisp/api.py:39: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
2017-04-20 17:47:16,156 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2017-04-20 17:47:17,725 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-04-20 17:47:17,737 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.

**Comment by doomedraven** [comment]
lol, post in correct repo, better use search there as that is reported already, and rc2 is too old, latest is 2.0.1

**Comment by jeandez** [comment]
Hello , 
I have installed the new version 2.0.1 but i am still facing the same issue : **error form the Cuckoo Guest : The analysis hit the critical timeout, terminating**

**Comment by doomedraven** [comment]
that is not cuckoo repository as Brad told already :D

**Comment by jeandez** [comment]
i do not quite understand.
What is not the correct repository ? you told me the latest version is 2.0.1.  i have installed it.

i used 2.0-rc2  before.

thx.

**Comment by lehuff** [comment]
This is for the spender-sandbox version of cuckoo. You are using the official version of cuckoo. Go here: https://github.com/cuckoosandbox/cuckoo
