### ISSUE TITLE
_connect() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [spender-sandbox/cuckoo-modified#277]
Recently just upgraded, did the database schema update and now I am having the following error on startup:

2016-09-07 13:33:28,719 [lib.cuckoo.core.resultserver] DEBUG: ResultServer running on 192.168.56.1:2042.
2016-09-07 13:33:28,720 [lib.cuckoo.core.scheduler] INFO: Using "esx" machine manager with max_analysis_count=0, max_machines_count=0, and max_vmstartup_count=10
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo-modified/cuckoo.py", line 132, in <module>
    cuckoo_main(max_analysis_count=args.max_analysis_count)
  File "/home/cuckoo/cuckoo-modified/cuckoo.py", line 78, in cuckoo_main
    sched.start()
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 578, in start
    self.initialize()
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/core/scheduler.py", line 546, in initialize
    machinery.initialize(machinery_name)
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/common/abstracts.py", line 329, in initialize
    super(LibVirtMachinery, self).initialize(module)
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/common/abstracts.py", line 97, in initialize
    self._initialize_check()
  File "/home/cuckoo/cuckoo-modified/modules/machinery/esx.py", line 28, in _initialize_check
    super(ESX, self)._initialize_check()
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/common/abstracts.py", line 341, in _initialize_check
    self.vms = self._fetch_machines()
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/common/abstracts.py", line 526, in _fetch_machines
    vms[vm.label] = self._lookup(vm.label)
  File "/home/cuckoo/cuckoo-modified/lib/cuckoo/common/abstracts.py", line 535, in _lookup
    conn = self._connect(label)
TypeError: _connect() takes exactly 1 argument (2 given)
/proc/self/fd/9: 4: exec: : not found

**Comment by spender-sandbox** [comment]
Pulled a commit that should fix it, can you confirm?

-Brad

**Comment by eoinmiller-sfdc** [comment]
Confirmed fixed! Thanks!
