### ISSUE TITLE
api error on on task create

### ISSUE THREAD

**Issue by marcurdy** [spender-sandbox/cuckoo-modified#279]
Creating a new task yields this error.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/cuckoo/cuckoo/utils/api.py", line 92, in tasks_create_file
    if int(enforce_timeout):
ValueError: invalid literal for int() with base 10: 'True'
XXXXXXXX - - [08/Sep/2016 16:27:07] "POST /tasks/create/file HTTP/1.1" 500 769

If I replace  "if int(enforce_timeout):" with  "if enforce_timeout:" it succeeds, but the desired intention may be lost.

**Comment by spender-sandbox** [comment]
Should be fixed now, thanks for the report!

-Brad
