### ISSUE TITLE
'VolatilityManager' object has no attribute 'zipdump'

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [spender-sandbox/cuckoo-modified#28]
Saw this in debug output with Volatility enabled:

2016-01-30 14:50:20,622 [modules.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo-modified/modules/processing/memory.py", line 1155, in run
    results = vol.run(manager=machine_manager, vm=task_machine)
  File "/home/cuckoo/cuckoo-modified/modules/processing/memory.py", line 1068, in run
    self.zipdump()
AttributeError: 'VolatilityManager' object has no attribute 'zipdump'

**Comment by spender-sandbox** [comment]
Thanks, fixed!

-Brad

**Comment by eoinmiller-sfdc** [comment]
Confirmed, thanks!
