### ISSUE TITLE
Remote Submit broken?

### ISSUE THREAD

**Issue by keithjjones** [spender-sandbox/cuckoo-modified#288]
I can't seem to submit samples remotely.  I'm submitting from a Windows 7 machine to a known working install of cuckoo-modified using utils\submit.py with --remote.  Here are some command lines:

This is through the api.py script on port 8090:

```
(python27-cog) C:\source\cuckoo-modified>python utils\submit.py --remote 10.0.0.144:8090 c:\Dirty\Sync\samples
Traceback (most recent call last):
  File "utils\submit.py", line 278, in <module>
    main()
  File "utils\submit.py", line 252, in main
    json = response.json()
  File "c:\python27-cog\lib\site-packages\requests\models.py", line 826, in json

    return complexjson.loads(self.text, **kwargs)
  File "c:\python27-cog\lib\site-packages\simplejson\__init__.py", line 516, in
loads
    return _default_decoder.decode(s)
  File "c:\python27-cog\lib\site-packages\simplejson\decoder.py", line 370, in d
ecode
    obj, end = self.raw_decode(s)
  File "c:\python27-cog\lib\site-packages\simplejson\decoder.py", line 400, in r
aw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 5 (char 5)
```

On this I get the following on the cuckoo server:

```
10.0.0.33 - - [19/Sep/2016 10:45:11] "POST /tasks/create/file HTTP/1.1" 500 759
Traceback (most recent call last):
  File "/Source/Python2/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Source/Python2/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "utils/api.py", line 89, in tasks_create_file
    if int(memory):
ValueError: invalid literal for int() with base 10: 'False'
```

When I aimed submit.py at the Django interface, I get a similar error:

```
(python27-cog) C:\source\cuckoo-modified>python utils\submit.py --remote 10.0.0.144:8000 c:\Dirty\Sync\samples\
Traceback (most recent call last):
  File "utils\submit.py", line 278, in <module>
    main()
  File "utils\submit.py", line 252, in main
    json = response.json()
  File "c:\python27-cog\lib\site-packages\requests\models.py", line 826, in json

    return complexjson.loads(self.text, **kwargs)
  File "c:\python27-cog\lib\site-packages\simplejson\__init__.py", line 516, in
loads
    return _default_decoder.decode(s)
  File "c:\python27-cog\lib\site-packages\simplejson\decoder.py", line 370, in d
ecode
    obj, end = self.raw_decode(s)
  File "c:\python27-cog\lib\site-packages\simplejson\decoder.py", line 400, in r
aw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

On this I get the following on the other end:

```
[19/Sep/2016 10:52:55] "POST /tasks/create/file HTTP/1.1" 404 3576
```

I have everything turned on inside api.conf and I verified it is working in the API page through the Django site.  I also have all servers listening correctly on the 10.0.0.144 host.

Am I doing something incorrectly or is this a bug?

Thanks!

Take care,
Keith

**Comment by doomedraven** [comment]
```
        if args.remote:
            if not HAVE_REQUESTS:
                print(bold(red("Error")) + ": you need to install python-requests (`pip install requests`)")
                return False

            if args.ssl:
                url = "https://{0}/tasks/create/url".format(args.remote)
            else:
                url = "http://{0}/tasks/create/url".format(args.remote)
```

it looks like it will puth against api.py instead of webgui integrated api


try change 

```
  File "utils/api.py", line 89, in tasks_create_file
    if int(memory):
ValueError: invalid literal for int() with base 10: 'False'
```

`if int(momery)` in like 89 to jsut `if memory`

**Comment by keithjjones** [comment]
@doomedraven nope, same error

**Comment by keithjjones** [comment]
```
Listening on http://10.0.0.144:8090/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "/Source/Python2/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Source/Python2/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "utils/api.py", line 92, in tasks_create_file
    if int(enforce_timeout):
ValueError: invalid literal for int() with base 10: 'False'
10.0.0.33 - - [19/Sep/2016 11:07:58] "POST /tasks/create/file HTTP/1.1" 500 759
```

**Comment by doomedraven** [comment]
as you can see is not the same, remove another `int()` here `if int(enforce_timeout):`

check if that kind of bug will hapepnd, remove anotehr ints if required

**Comment by doomedraven** [comment]
try replace `json["task_id"]` by json["task_ids"] as test

try adding pring of values before error lines to debug it

**Comment by keithjjones** [comment]
When merged, yes.  It worked for me.  I don't have more than one instance to test it on though.
