### ISSUE TITLE
still getting a lot of invalid state exceptions from process.py

### ISSUE THREAD

**Issue by mallorybobalice** [spender-sandbox/cuckoo-modified#302]
after rewrapping cuckoo resproc into its own service in lts 16.04 noticed this happens rather frequently again (latest kernel updates, libraries, stable mongo, mysql,code base for cm and pip libararies (plus yara,libvirt etc from latest stable source) ). This has been happening for about a year now... 

/usr/bin/python2.7 ./utils/process.py -d -p 5 auto

this is driving me absolutely insane because it seems to aborting processing half way and results in quite a bit of re-work... is there anything we can do to diagnose this better ... Guessing we won't be really moving to the cuckoosandbox processing 2 any time soon? (or you guys are all running distributed nodes with child vms and aren't really concerned about process.py (if that uses dist.py without process.py) 

````
Sep 26 18:50:18 puppieshost1 python2.7[7337]: 2016-09-26 18:50:18,990 [root] INFO: Task #127113: reports generation completed
Sep 26 18:50:18 puppieshost1 python2.7[7337]: 2016-09-26 18:50:18,998 [root] INFO: Processing analysis data for Task #127111
Sep 26 18:50:19 puppieshost1 python2.7[7337]: 2016-09-26 18:50:19,010 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "Decompression" on analysis at "storage/analyses/127111"
Sep 26 18:50:19 puppieshost1 python2.7[7337]: 2016-09-26 18:50:19,011 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "AnalysisInfo" on analysis at "storage/analyses/127111"
Sep 26 18:50:19 puppieshost1 python2.7[7337]: Traceback (most recent call last):
Sep 26 18:50:19 puppieshost1 python2.7[7337]:   File "./utils/process.py", line 235, in <module>
Sep 26 18:50:19 puppieshost1 python2.7[7337]:     main()
Sep 26 18:50:19 puppieshost1 python2.7[7337]:   File "./utils/process.py", line 225, in main
Sep 26 18:50:19 puppieshost1 python2.7[7337]:     autoprocess(parallel=args.parallel)
Sep 26 18:50:19 puppieshost1 python2.7[7337]:   File "./utils/process.py", line 211, in autoprocess
Sep 26 18:50:19 puppieshost1 python2.7[7337]:     pool.join()
Sep 26 18:50:19 puppieshost1 python2.7[7337]:   File "/usr/lib/python2.7/multiprocessing/pool.py", line 469, in join
Sep 26 18:50:19 puppieshost1 python2.7[7337]:     assert self._state in (CLOSE, TERMINATE)
Sep 26 18:50:19 puppieshost1 python2.7[7337]: AssertionError
Sep 26 18:50:19 puppieshost1 python2.7[7337]: 2016-09-26 18:50:19,042 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "BehaviorAnalysis" on analysis at "storage/analyses/127111"
Sep 26 18:50:19 puppieshost1 python2.7[7228]: 2016-09-26 18:50:19,529 [lib.cuckoo.core.guest] DEBUG: PUPPIES_w7x64_1: analysis not completed yet (status=2)
Sep 26 18:50:19 puppieshost1 systemd[1]: cuckooresproc.service: Main process exited, code=exited, status=1/FAILURE
Sep 26 18:50:19 puppieshost1 systemd[1]: cuckooresproc.service: Unit entered failed state.
Sep 26 18:50:19 puppieshost1 systemd[1]: cuckooresproc.service: Failed with result 'exit-code'.

Sep 26 18:54:26 puppieshost1 python2.7[8070]: 2016-09-26 18:54:26,966 [root] INFO: Task #127111: reports generation completed
Sep 26 18:54:26 puppieshost1 python2.7[8070]: 2016-09-26 18:54:26,966 [root] INFO: Task #127116: reports generation completed
Sep 26 18:54:26 puppieshost1 python2.7[8070]: 2016-09-26 18:54:26,975 [root] INFO: Processing analysis data for Task #127121
Sep 26 18:54:26 puppieshost1 python2.7[8660]: 2016-09-26 18:54:26,981 [lib.cuckoo.core.resultserver] DEBUG: New connection from: xxx.xxx.xxx.xxx:49176
Sep 26 18:54:26 puppieshost1 python2.7[8660]: 2016-09-26 18:54:26,981 [lib.cuckoo.core.resultserver] DEBUG: File upload request for shots/0007.jpg
Sep 26 18:54:26 puppieshost1 python2.7[8070]: 2016-09-26 18:54:26,994 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "Decompression" on analysis at "storage/analyses/127121"
Sep 26 18:54:27 puppieshost1 python2.7[8070]: 2016-09-26 18:54:27,004 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "AnalysisInfo" on analysis at "storage/analyses/127121"
Sep 26 18:54:27 puppieshost1 python2.7[8070]: Traceback (most recent call last):
Sep 26 18:54:27 puppieshost1 python2.7[8070]:   File "./utils/process.py", line 235, in <module>
Sep 26 18:54:27 puppieshost1 python2.7[8070]:     main()
Sep 26 18:54:27 puppieshost1 python2.7[8070]:   File "./utils/process.py", line 225, in main
Sep 26 18:54:27 puppieshost1 python2.7[8070]:     autoprocess(parallel=args.parallel)
Sep 26 18:54:27 puppieshost1 python2.7[8070]:   File "./utils/process.py", line 211, in autoprocess
Sep 26 18:54:27 puppieshost1 python2.7[8070]:     pool.join()
Sep 26 18:54:27 puppieshost1 python2.7[8070]:   File "/usr/lib/python2.7/multiprocessing/pool.py", line 469, in join
Sep 26 18:54:27 puppieshost1 python2.7[8070]:     assert self._state in (CLOSE, TERMINATE)
Sep 26 18:54:27 puppieshost1 python2.7[8070]: AssertionError
Sep 26 18:54:27 puppieshost1 python2.7[8070]: 2016-09-26 18:54:27,022 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "BehaviorAnalysis" on analysis at "storage/analyses/127121"
Sep 26 18:54:27 puppieshost1 python2.7[8660]: 2016-09-26 18:54:27,133 [lib.cuckoo.core.resultserver] DEBUG: Uploaded file length: 50401
Sep 26 18:54:27 puppieshost1 python2.7[8660]: 2016-09-26 18:54:27,134 [lib.cuckoo.core.resultserver] DEBUG: Connection closed: xxx.xxx.xxx.xxx:49176
Sep 26 18:54:27 puppieshost1 python2.7[8660]: 2016-09-26 18:54:27,243 [lib.cuckoo.core.guest] DEBUG: PUPPIES_w7x64_6: analysis not completed yet (status=2)
Sep 26 18:54:27 puppieshost1 python2.7[8660]: 2016-09-26 18:54:27,253 [lib.cuckoo.core.guest] DEBUG: PUPPIES_w7x64_4: analysis not completed yet (status=2)
Sep 26 18:54:27 puppieshost1 python2.7[8660]: 2016-09-26 18:54:27,309 [lib.cuckoo.core.guest] DEBUG: PUPPIES_w7x64_3: analysis not completed yet (status=2)
Sep 26 18:54:27 puppieshost1 systemd[1]: cuckooresproc.service: Main process exited, code=exited, status=1/FAILURE
Sep 26 18:54:27 puppieshost1 systemd[1]: cuckooresproc.service: Unit entered failed state.
Sep 26 18:54:27 puppieshost1 systemd[1]: cuckooresproc.service: Failed with result 'exit-code'.
````

````
2016-09-26 17:17:52,474 [root] INFO: Task #127031: reports generation completed
2016-09-26 17:17:52,483 [root] INFO: Processing analysis data for Task #127034
2016-09-26 17:18:05,654 [root] INFO: Processing analysis data for Task #126884
2016-09-26 17:18:05,677 [root] INFO: Processing analysis data for Task #127033
2016-09-26 17:18:05,688 [root] INFO: Processing analysis data for Task #127036
2016-09-26 17:18:05,698 [root] INFO: Processing analysis data for Task #127028
2016-09-26 17:18:05,710 [root] INFO: Processing analysis data for Task #127034
2016-09-26 17:19:50,806 [root] INFO: Task #127036: reports generation completed
2016-09-26 17:19:50,806 [root] INFO: Task #127028: reports generation completed
2016-09-26 17:19:50,817 [root] INFO: Processing analysis data for Task #127035
2016-09-26 17:19:50,853 [root] INFO: Processing analysis data for Task #127042
2016-09-26 17:20:10,886 [root] INFO: Task #127033: reports generation completed
2016-09-26 17:20:10,886 [root] INFO: Task #127034: reports generation completed
2016-09-26 17:20:10,896 [root] INFO: Processing analysis data for Task #127041
2016-09-26 17:20:10,920 [root] INFO: Processing analysis data for Task #127037
2016-09-26 17:21:26,022 [root] INFO: Task #127042: reports generation completed
2016-09-26 17:21:26,031 [root] INFO: Processing analysis data for Task #127038
2016-09-26 17:21:39,322 [root] INFO: Processing analysis data for Task #126884
2016-09-26 17:21:39,337 [root] INFO: Processing analysis data for Task #127035
2016-09-26 17:21:39,347 [root] INFO: Processing analysis data for Task #127041
2016-09-26 17:21:39,357 [root] INFO: Processing analysis data for Task #127037
2016-09-26 17:21:39,385 [root] INFO: Processing analysis data for Task #127038
2016-09-26 17:23:44,490 [root] INFO: Task #127035: reports generation completed
2016-09-26 17:23:44,490 [root] INFO: Task #127037: reports generation completed
2016-09-26 17:23:44,500 [root] INFO: Processing analysis data for Task #127040
2016-09-26 17:23:44,510 [root] INFO: Processing analysis data for Task #127039
2016-09-26 17:23:49,536 [root] INFO: Task #127038: reports generation completed
2016-09-26 17:23:49,545 [root] INFO: Processing analysis data for Task #127043
2016-09-26 17:23:54,552 [root] INFO: Task #127041: reports generation completed
2016-09-26 17:23:54,561 [root] INFO: Processing analysis data for Task #127046
2016-09-26 17:25:49,658 [root] INFO: Task #127046: reports generation completed
2016-09-26 17:25:49,672 [root] INFO: Processing analysis data for Task #127044
2016-09-26 17:26:02,453 [root] INFO: Processing analysis data for Task #126884
2016-09-26 17:26:02,467 [root] INFO: Processing analysis data for Task #127040
2016-09-26 17:26:02,477 [root] INFO: Processing analysis data for Task #127039
2016-09-26 17:26:02,487 [root] INFO: Processing analysis data for Task #127043
2016-09-26 17:26:02,499 [root] INFO: Processing analysis data for Task #127044
2016-09-26 17:27:52,590 [root] INFO: Task #127044: reports generation completed
2016-09-26 17:27:52,600 [root] INFO: Processing analysis data for Task #127045
2016-09-26 17:28:07,627 [root] INFO: Task #127039: reports generation completed
2016-09-26 17:28:07,636 [root] INFO: Processing analysis data for Task #127051
2016-09-26 17:28:12,642 [root] INFO: Task #127040: reports generation completed
2016-09-26 17:28:12,642 [root] INFO: Task #127043: reports generation completed
2016-09-26 17:28:12,651 [root] INFO: Processing analysis data for Task #127054
2016-09-26 17:28:12,673 [root] INFO: Processing analysis data for Task #127055
2016-09-26 17:29:32,754 [root] INFO: Task #127051: reports generation completed
2016-09-26 17:29:32,769 [root] INFO: Processing analysis data for Task #127047
2016-09-26 17:29:45,552 [root] INFO: Processing analysis data for Task #126884
2016-09-26 17:29:45,567 [root] INFO: Processing analysis data for Task #127045
2016-09-26 17:29:45,576 [root] INFO: Processing analysis data for Task #127054
2016-09-26 17:29:45,586 [root] INFO: Processing analysis data for Task #127055
2016-09-26 17:29:45,598 [root] INFO: Processing analysis data for Task #127047
2016-09-26 17:31:45,702 [root] INFO: Task #127047: reports generation completed
2016-09-26 17:31:45,718 [root] INFO: Processing analysis data for Task #127049
2016-09-26 17:31:55,734 [root] INFO: Task #127045: reports generation completed
2016-09-26 17:31:55,745 [root] INFO: Processing analysis data for Task #127048
2016-09-26 17:32:00,750 [root] INFO: Task #127054: reports generation completed
2016-09-26 17:32:00,759 [root] INFO: Processing analysis data for Task #127050
2016-09-26 17:32:15,773 [root] INFO: Task #127055: reports generation completed
2016-09-26 17:32:15,784 [root] INFO: Processing analysis data for Task #127053
2016-09-26 17:34:10,922 [root] INFO: Task #127049: reports generation completed
2016-09-26 17:34:10,922 [root] INFO: Task #127048: reports generation completed
2016-09-26 17:34:10,932 [root] INFO: Processing analysis data for Task #127052
2016-09-26 17:34:23,999 [root] INFO: Processing analysis data for Task #126884
2016-09-26 17:34:24,013 [root] INFO: Processing analysis data for Task #127050
2016-09-26 17:34:24,023 [root] INFO: Processing analysis data for Task #127053
2016-09-26 17:34:24,032 [root] INFO: Processing analysis data for Task #127052
2016-09-26 17:34:24,044 [root] INFO: Processing analysis data for Task #127056
2016-09-26 17:36:04,122 [root] INFO: Task #127056: reports generation completed
2016-09-26 17:36:04,143 [root] INFO: Processing analysis data for Task #127063
2016-09-26 17:36:29,166 [root] INFO: Task #127052: reports generation completed
2016-09-26 17:36:29,174 [root] INFO: Processing analysis data for Task #127059
2016-09-26 17:36:34,190 [root] INFO: Task #127050: reports generation completed
2016-09-26 17:36:34,190 [root] INFO: Task #127053: reports generation completed
2016-09-26 17:36:34,311 [root] INFO: Processing analysis data for Task #127060
2016-09-26 17:36:34,331 [root] INFO: Processing analysis data for Task #127057
2016-09-26 17:37:19,374 [root] INFO: Task #127063: reports generation completed
2016-09-26 17:37:19,384 [root] INFO: Processing analysis data for Task #127058
2016-09-26 17:37:32,200 [root] INFO: Processing analysis data for Task #126884
2016-09-26 17:37:32,215 [root] INFO: Processing analysis data for Task #127059
2016-09-26 17:37:32,225 [root] INFO: Processing analysis data for Task #127060
2016-09-26 17:37:32,235 [root] INFO: Processing analysis data for Task #127057
2016-09-26 17:37:32,246 [root] INFO: Processing analysis data for Task #127058
2016-09-26 17:39:07,326 [root] INFO: Task #127058: reports generation completed
2016-09-26 17:39:07,366 [root] INFO: Processing analysis data for Task #127062
2016-09-26 17:39:22,382 [root] INFO: Task #127057: reports generation completed
2016-09-26 17:39:22,390 [root] INFO: Processing analysis data for Task #127066
2016-09-26 17:39:32,402 [root] INFO: Task #127059: reports generation completed
2016-09-26 17:39:32,412 [root] INFO: Processing analysis data for Task #127064
2016-09-26 17:40:52,482 [root] INFO: Task #127060: reports generation completed
2016-09-26 17:40:52,523 [root] INFO: Processing analysis data for Task #127061
2016-09-26 17:41:07,546 [root] INFO: Task #127062: reports generation completed
2016-09-26 17:41:07,556 [root] INFO: Processing analysis data for Task #127065
2016-09-26 17:41:20,538 [root] INFO: Processing analysis data for Task #126884
2016-09-26 17:41:20,556 [root] INFO: Processing analysis data for Task #127066
2016-09-26 17:41:20,567 [root] INFO: Processing analysis data for Task #127064
2016-09-26 17:41:20,580 [root] INFO: Processing analysis data for Task #127061
2016-09-26 17:41:20,617 [root] INFO: Processing analysis data for Task #127065
2016-09-26 17:43:00,698 [root] INFO: Task #127065: reports generation completed
2016-09-26 17:43:00,707 [root] INFO: Processing analysis data for Task #127071
2016-09-26 17:43:05,714 [root] INFO: Task #127066: reports generation completed
2016-09-26 17:43:05,746 [root] INFO: Processing analysis data for Task #127067
2016-09-26 17:46:10,677 [root] INFO: Processing analysis data for Task #126884
2016-09-26 17:46:10,692 [root] INFO: Processing analysis data for Task #127064
2016-09-26 17:46:10,702 [root] INFO: Processing analysis data for Task #127061
2016-09-26 17:46:10,713 [root] INFO: Processing analysis data for Task #127071
2016-09-26 17:46:10,725 [root] INFO: Processing analysis data for Task #127067
2016-09-26 17:47:35,851 [root] INFO: Task #127067: reports generation completed
2016-09-26 17:47:35,911 [root] INFO: Processing analysis data for Task #127069
2016-09-26 17:48:30,962 [root] INFO: Task #127069: reports generation completed
2016-09-26 17:48:30,972 [root] INFO: Processing analysis data for Task #127068
2016-09-26 17:48:35,982 [root] INFO: Task #127071: reports generation completed
2016-09-26 17:48:36,002 [root] INFO: Processing analysis data for Task #127070
2016-09-26 17:49:16,034 [root] INFO: Task #127061: reports generation completed
2016-09-26 17:49:16,043 [root] INFO: Processing analysis data for Task #127072
2016-09-26 17:50:06,086 [root] INFO: Task #127064: reports generation completed
2016-09-26 17:50:06,095 [root] INFO: Processing analysis data for Task #127073
2016-09-26 17:50:19,853 [root] INFO: Processing analysis data for Task #126884
2016-09-26 17:50:19,866 [root] INFO: Processing analysis data for Task #127068
2016-09-26 17:50:19,876 [root] INFO: Processing analysis data for Task #127070
2016-09-26 17:50:19,886 [root] INFO: Processing analysis data for Task #127072
2016-09-26 17:50:19,897 [root] INFO: Processing analysis data for Task #127073
2016-09-26 17:52:24,998 [root] INFO: Task #127070: reports generation completed
2016-09-26 17:52:25,007 [root] INFO: Processing analysis data for Task #127074
2016-09-26 17:54:17,604 [root] INFO: Processing analysis data for Task #126884
2016-09-26 17:56:52,753 [root] INFO: Task #126884: reports generation completed
2016-09-26 17:56:52,764 [root] INFO: Processing analysis data for Task #127068
2016-09-26 17:58:12,836 [root] INFO: Task #127068: reports generation completed
2016-09-26 17:58:12,846 [root] INFO: Processing analysis data for Task #127072
2016-09-26 17:59:37,921 [root] INFO: Task #127072: reports generation completed
2016-09-26 17:59:37,931 [root] INFO: Processing analysis data for Task #127073
2016-09-26 18:01:03,006 [root] INFO: Task #127073: reports generation completed
2016-09-26 18:01:03,015 [root] INFO: Processing analysis data for Task #127074
2016-09-26 18:01:58,068 [root] INFO: Task #127074: reports generation completed
2016-09-26 18:01:58,079 [root] INFO: Processing analysis data for Task #127075
2016-09-26 18:03:13,142 [root] INFO: Task #127075: reports generation completed
2016-09-26 18:03:13,151 [root] INFO: Processing analysis data for Task #127076
2016-09-26 18:04:28,217 [root] INFO: Task #127076: reports generation completed
2016-09-26 18:04:28,226 [root] INFO: Processing analysis data for Task #127083
2016-09-26 18:05:28,286 [root] INFO: Task #127083: reports generation completed
2016-09-26 18:05:28,297 [root] INFO: Processing analysis data for Task #127077
2016-09-26 18:06:48,384 [root] INFO: Task #127077: reports generation completed
2016-09-26 18:06:48,394 [root] INFO: Processing analysis data for Task #127079
2016-09-26 18:16:09,363 [root] INFO: Processing analysis data for Task #127079
2016-09-26 18:16:59,408 [root] INFO: Task #127079: reports generation completed
2016-09-26 18:16:59,419 [root] INFO: Processing analysis data for Task #127080
2016-09-26 18:18:14,502 [root] INFO: Task #127080: reports generation completed
2016-09-26 18:18:14,513 [root] INFO: Processing analysis data for Task #127081
2016-09-26 18:26:23,316 [root] INFO: Processing analysis data for Task #127081
2016-09-26 18:33:38,103 [root] INFO: Processing analysis data for Task #127081
2016-09-26 18:33:38,119 [root] INFO: Processing analysis data for Task #127085
2016-09-26 18:33:38,130 [root] INFO: Processing analysis data for Task #127082
2016-09-26 18:33:38,142 [root] INFO: Processing analysis data for Task #127078
2016-09-26 18:33:38,154 [root] INFO: Processing analysis data for Task #127086
2016-09-26 18:35:28,246 [root] INFO: Task #127082: reports generation completed
2016-09-26 18:35:28,261 [root] INFO: Processing analysis data for Task #127084
2016-09-26 18:35:58,298 [root] INFO: Task #127081: reports generation completed
2016-09-26 18:35:58,308 [root] INFO: Processing analysis data for Task #127090
2016-09-26 18:36:03,314 [root] INFO: Task #127085: reports generation completed
2016-09-26 18:36:03,314 [root] INFO: Task #127078: reports generation completed
2016-09-26 18:36:03,324 [root] INFO: Processing analysis data for Task #127094
2016-09-26 18:36:03,338 [root] INFO: Processing analysis data for Task #127087
2016-09-26 18:36:13,350 [root] INFO: Task #127086: reports generation completed
2016-09-26 18:36:13,359 [root] INFO: Processing analysis data for Task #127088
2016-09-26 18:36:27,453 [root] INFO: Processing analysis data for Task #127084
2016-09-26 18:36:27,471 [root] INFO: Processing analysis data for Task #127090
2016-09-26 18:36:27,486 [root] INFO: Processing analysis data for Task #127094
2016-09-26 18:36:27,497 [root] INFO: Processing analysis data for Task #127087
2016-09-26 18:36:27,512 [root] INFO: Processing analysis data for Task #127088
2016-09-26 18:38:47,706 [root] INFO: Task #127094: reports generation completed
2016-09-26 18:38:47,730 [root] INFO: Processing analysis data for Task #127091
2016-09-26 18:39:02,754 [root] INFO: Task #127090: reports generation completed
2016-09-26 18:39:02,754 [root] INFO: Task #127087: reports generation completed
2016-09-26 18:39:02,765 [root] INFO: Processing analysis data for Task #127093
2016-09-26 18:39:02,785 [root] INFO: Processing analysis data for Task #127095
2016-09-26 18:39:07,802 [root] INFO: Task #127084: reports generation completed
2016-09-26 18:39:07,802 [root] INFO: Task #127088: reports generation completed
2016-09-26 18:39:07,811 [root] INFO: Processing analysis data for Task #127092
2016-09-26 18:39:07,820 [root] INFO: Processing analysis data for Task #127089
2016-09-26 18:39:26,981 [root] INFO: Processing analysis data for Task #127091
2016-09-26 18:39:26,994 [root] INFO: Processing analysis data for Task #127093
2016-09-26 18:39:27,004 [root] INFO: Processing analysis data for Task #127095
2016-09-26 18:39:27,015 [root] INFO: Processing analysis data for Task #127092
2016-09-26 18:39:27,026 [root] INFO: Processing analysis data for Task #127089
2016-09-26 18:41:32,130 [root] INFO: Task #127092: reports generation completed
2016-09-26 18:41:32,143 [root] INFO: Processing analysis data for Task #127096
2016-09-26 18:41:42,158 [root] INFO: Task #127089: reports generation completed
2016-09-26 18:41:42,169 [root] INFO: Processing analysis data for Task #127099
2016-09-26 18:41:47,174 [root] INFO: Task #127091: reports generation completed
2016-09-26 18:41:47,174 [root] INFO: Task #127093: reports generation completed
2016-09-26 18:41:47,183 [root] INFO: Processing analysis data for Task #127100
2016-09-26 18:41:47,196 [root] INFO: Processing analysis data for Task #127103
2016-09-26 18:41:52,213 [root] INFO: Task #127095: reports generation completed
2016-09-26 18:41:52,225 [root] INFO: Processing analysis data for Task #127104
2016-09-26 18:42:06,500 [root] INFO: Processing analysis data for Task #127096
2016-09-26 18:42:06,519 [root] INFO: Processing analysis data for Task #127099
2016-09-26 18:42:06,529 [root] INFO: Processing analysis data for Task #127100
2016-09-26 18:42:06,541 [root] INFO: Processing analysis data for Task #127103
2016-09-26 18:42:06,553 [root] INFO: Processing analysis data for Task #127104
2016-09-26 18:44:16,662 [root] INFO: Task #127099: reports generation completed
2016-09-26 18:44:16,662 [root] INFO: Task #127100: reports generation completed
2016-09-26 18:44:16,662 [root] INFO: Task #127103: reports generation completed
2016-09-26 18:44:16,662 [root] INFO: Task #127104: reports generation completed
2016-09-26 18:44:16,672 [root] INFO: Processing analysis data for Task #127105
2016-09-26 18:44:16,682 [root] INFO: Processing analysis data for Task #127098
2016-09-26 18:44:16,692 [root] INFO: Processing analysis data for Task #127101
2016-09-26 18:44:16,702 [root] INFO: Processing analysis data for Task #127102
2016-09-26 18:44:21,738 [root] INFO: Task #127096: reports generation completed
2016-09-26 18:44:21,746 [root] INFO: Processing analysis data for Task #127106
2016-09-26 18:44:35,572 [root] INFO: Processing analysis data for Task #127105
2016-09-26 18:44:35,587 [root] INFO: Processing analysis data for Task #127098
2016-09-26 18:44:35,597 [root] INFO: Processing analysis data for Task #127101
2016-09-26 18:44:35,608 [root] INFO: Processing analysis data for Task #127102
2016-09-26 18:44:35,630 [root] INFO: Processing analysis data for Task #127106
2016-09-26 18:46:30,738 [root] INFO: Task #127101: reports generation completed
2016-09-26 18:46:30,738 [root] INFO: Task #127102: reports generation completed
2016-09-26 18:46:30,750 [root] INFO: Processing analysis data for Task #127097
2016-09-26 18:46:30,790 [root] INFO: Processing analysis data for Task #127107
2016-09-26 18:46:35,798 [root] INFO: Task #127106: reports generation completed
2016-09-26 18:46:35,807 [root] INFO: Processing analysis data for Task #127109
2016-09-26 18:46:50,822 [root] INFO: Task #127098: reports generation completed
2016-09-26 18:46:50,854 [root] INFO: Processing analysis data for Task #127112
2016-09-26 18:47:35,894 [root] INFO: Task #127105: reports generation completed
2016-09-26 18:47:35,904 [root] INFO: Processing analysis data for Task #127113
2016-09-26 18:47:48,726 [root] INFO: Processing analysis data for Task #127097
2016-09-26 18:47:48,744 [root] INFO: Processing analysis data for Task #127107
2016-09-26 18:47:48,753 [root] INFO: Processing analysis data for Task #127109
2016-09-26 18:47:48,765 [root] INFO: Processing analysis data for Task #127112
2016-09-26 18:47:48,778 [root] INFO: Processing analysis data for Task #127113
2016-09-26 18:49:53,906 [root] INFO: Task #127097: reports generation completed
2016-09-26 18:49:53,906 [root] INFO: Task #127109: reports generation completed
2016-09-26 18:49:53,916 [root] INFO: Processing analysis data for Task #127108
2016-09-26 18:49:53,928 [root] INFO: Processing analysis data for Task #127110
2016-09-26 18:49:58,935 [root] INFO: Task #127107: reports generation completed
2016-09-26 18:49:58,935 [root] INFO: Task #127112: reports generation completed
2016-09-26 18:49:58,944 [root] INFO: Processing analysis data for Task #127114
2016-09-26 18:49:58,969 [root] INFO: Processing analysis data for Task #127115
2016-09-26 18:50:18,990 [root] INFO: Task #127113: reports generation completed
2016-09-26 18:50:18,998 [root] INFO: Processing analysis data for Task #127111
2016-09-26 18:50:31,635 [root] INFO: Processing analysis data for Task #127108
2016-09-26 18:50:31,651 [root] INFO: Processing analysis data for Task #127110
2016-09-26 18:50:31,661 [root] INFO: Processing analysis data for Task #127114
2016-09-26 18:50:31,671 [root] INFO: Processing analysis data for Task #127115
2016-09-26 18:50:31,690 [root] INFO: Processing analysis data for Task #127111
2016-09-26 18:52:21,782 [root] INFO: Task #127114: reports generation completed
2016-09-26 18:52:21,782 [root] INFO: Task #127115: reports generation completed
2016-09-26 18:52:21,791 [root] INFO: Processing analysis data for Task #127116
2016-09-26 18:52:21,825 [root] INFO: Processing analysis data for Task #127119
2016-09-26 18:52:26,830 [root] INFO: Task #127110: reports generation completed
2016-09-26 18:52:26,843 [root] INFO: Processing analysis data for Task #127122
2016-09-26 18:52:46,870 [root] INFO: Task #127108: reports generation completed
2016-09-26 18:52:46,884 [root] INFO: Processing analysis data for Task #127124
2016-09-26 18:54:26,966 [root] INFO: Task #127111: reports generation completed
2016-09-26 18:54:26,966 [root] INFO: Task #127116: reports generation completed
2016-09-26 18:54:26,975 [root] INFO: Processing analysis data for Task #127121
2016-09-26 18:54:39,496 [root] INFO: Processing analysis data for Task #127119
2016-09-26 18:54:39,511 [root] INFO: Processing analysis data for Task #127122
2016-09-26 18:54:39,521 [root] INFO: Processing analysis data for Task #127124
2016-09-26 18:54:39,534 [root] INFO: Processing analysis data for Task #127121
2016-09-26 18:54:39,552 [root] INFO: Processing analysis data for Task #127123
2016-09-26 18:56:39,674 [root] INFO: Task #127119: reports generation completed
2016-09-26 18:56:39,674 [root] INFO: Task #127122: reports generation completed
2016-09-26 18:56:39,674 [root] INFO: Task #127124: reports generation completed
2016-09-26 18:56:39,685 [root] INFO: Processing analysis data for Task #127117
2016-09-26 18:56:39,720 [root] INFO: Processing analysis data for Task #127118
2016-09-26 18:56:39,746 [root] INFO: Processing analysis data for Task #127120
2016-09-26 18:57:24,786 [root] INFO: Task #127121: reports generation completed
2016-09-26 18:57:24,786 [root] INFO: Task #127123: reports generation completed
2016-09-26 18:57:24,814 [root] INFO: Processing analysis data for Task #127126
2016-09-26 18:57:24,843 [root] INFO: Processing analysis data for Task #127125
2016-09-26 18:57:37,573 [root] INFO: Processing analysis data for Task #127117
2016-09-26 18:57:37,587 [root] INFO: Processing analysis data for Task #127118
2016-09-26 18:57:37,596 [root] INFO: Processing analysis data for Task #127120
2016-09-26 18:57:37,606 [root] INFO: Processing analysis data for Task #127126
2016-09-26 18:57:37,618 [root] INFO: Processing analysis data for Task #127125
````

**Comment by mallorybobalice** [comment]
anyone? 

seems to be leading to certain tasks being left in the queue and worst case the queue completely locking up. no real indication where it happens or why. guessing i should go add some print statements. 

please help :( ?

**Comment by doomedraven** [comment]
try one thing, `/usr/bin/python2.7 ./utils/process.py -d -p5 auto` no space between 5 and -p

**Comment by mallorybobalice** [comment]
=( hasn't helped. thanks though
