### ISSUE TITLE
No database backend reporting module is enabled! Please enable either ElasticSearch or MongoDB.

### ISSUE THREAD

**Issue by obdnanr** [spender-sandbox/cuckoo-modified#342]
How do I enable Elasticsearch?

/opt/cuckoo-modified/web$ sudo python ./manage.py runserver 10.10.10.10:80 &
:/opt/cuckoo-modified/web$ Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/cuckoo-modified/web/web/settings.py", line 22, in <module>
    raise Exception("**No database backend reporting module is enabled! Please enable either ElasticSearch or MongoDB.")
Exception: No database backend reporting module is enabled! Please enable either ElasticSearch or MongoDB.**

**Comment by doomedraven** [comment]
check 
conf/reporing.conf

**Comment by obdnanr** [comment]
Thanks!

**Comment by doomedraven** [comment]
if solved, close ;)
