### ISSUE TITLE
Error: adding task to database

### ISSUE THREAD

**Issue by kkburg** [spender-sandbox/cuckoo-modified#35]
Hello,

when i try to submit a File I was getting the following error:

`lib.cuckoo.common.exceptions.CuckooDatabaseError: DB schema version mismatch: found 4b09c454108c, expected f111620bb8. Try to apply all migrations (cd utils/db_migration/ && alembic upgrade `head).`

When i changed the Schematic Version in database.py to "4b09c454108c" and since then I'm getting this error:

`Error: adding task to database`

How do I fix this?

**Comment by housemusic42** [comment]
hi kkburg - the answer is in the error:
```Try to apply all migrations cd utils/db_migration/ && alembic upgradehead```

**Comment by kkburg** [comment]
Hello,
i tried that, but then i get

```
cuckoo@virusschleuder01:/media/cuckoo/cuckoo_nest/cuckoo1.3_spender/utils/db_migration$ sudo alembic upgrade head
[sudo] password for cuckoo: 
INFO  [alembic.migration] Context impl MySQLImpl.
INFO  [alembic.migration] Will assume non-transactional DDL.
cuckoo@virusschleuder01:/media/cuckoo/cuckoo_nest/cuckoo1.3_spender/utils/db_migration$ python /media/cuckoo/cuckoo_nest/cuckoo1.3_spender/utils/submit.py /home/cuckoo/Desktop/Malware/Resume.rtf 
Traceback (most recent call last):
  File "/media/cuckoo/cuckoo_nest/cuckoo1.3_spender/utils/submit.py", line 278, in <module>
    main()
  File "/media/cuckoo/cuckoo_nest/cuckoo1.3_spender/utils/submit.py", line 72, in main
    db = Database()
  File "/media/cuckoo/cuckoo_nest/cuckoo1.3_spender/utils/../lib/cuckoo/common/utils.py", line 1533, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/media/cuckoo/cuckoo_nest/cuckoo1.3_spender/utils/../lib/cuckoo/core/database.py", line 419, in __init__
    SCHEMA_VERSION))
lib.cuckoo.common.exceptions.CuckooDatabaseError: DB schema version mismatch: found f111620bb8, expected 4b09c454108c. Try to apply all migrations (cd utils/db_migration/ && alembic upgrade head).
```

again until i fix the Schmematic Versio
