### ISSUE TITLE
invalid string pointer 0x020A1A5000000000

### ISSUE THREAD

**Issue by obdnanr** [spender-sandbox/cuckoo-modified#351]
Hey,

When I try to run word docs or URL's I get this error:

    Error: Analysis failed: invalid string pointer 0x020A1A5000000000

2016-11-01 09:49:47,062 [root] INFO: Date set to: 11-01-16, time set to: 13:49:47
2016-11-01 09:49:47,717 [root] ERROR: Traceback (most recent call last):
  File "C:\nieqsevx\analyzer.py", line 1150, in <module>
    analyzer.prepare()
  File "C:\nieqsevx\analyzer.py", line 816, in prepare
    svcpid = self.pids_from_process_name_list(["services.exe"])
  File "C:\nieqsevx\analyzer.py", line 755, in pids_from_process_name_list
    proclist.append((proc.ImageName.Buffer[:proc.ImageName.Length/2], proc.UniqueProcessId))
ValueError: invalid string pointer 0x020A1A5000000000
Traceback (most recent call last):
  File "C:\nieqsevx\analyzer.py", line 1150, in <module>
    analyzer.prepare()
  File "C:\nieqsevx\analyzer.py", line 816, in prepare
    svcpid = self.pids_from_process_name_list(["services.exe"])
  File "C:\nieqsevx\analyzer.py", line 755, in pids_from_process_name_list
    proclist.append((proc.ImageName.Buffer[:proc.ImageName.Length/2], proc.UniqueProcessId))
ValueError: invalid string pointer 0x020A1A5000000000

**Comment by spender-sandbox** [comment]
What's the guest OS version?

-Brad

**Comment by obdnanr** [comment]
Two Windows 7 64bit, with office 2010.

**Comment by spender-sandbox** [comment]
And it's a 32-bit version of python installed in the guest?

-Brad

**Comment by obdnanr** [comment]
It's MSC V.1500 64bit (AMD64) on win32.

**Comment by spender-sandbox** [comment]
Only 32bit versions of Python are supported in the guest.

-Brad

**Comment by obdnanr** [comment]
I swapped the python to 32bit, and I get the same error.

**Comment by spender-sandbox** [comment]
Not possible, it's printing a 64bit pointer.

-Brad
