### ISSUE TITLE
maec reporting module - max recursion depth exceeded errors

### ISSUE THREAD

**Issue by mallorybobalice** [spender-sandbox/cuckoo-modified#57]
Hi, 

we have the MAEC reporting module enabled for the time being (although thinking of migrating off it,  it might take a while)... 
Was wondering if anyone else was seeing the following type of errors for it:

```
2016-02-15 17:17:03,510 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MAEC41Report":
Traceback (most recent call last):
  File "/home/kittens/utils/../lib/cuckoo/core/plugins.py", line 630, in process
    current.run(self.results)
  File "/home/kittens/utils/../modules/reporting/maec41.py", line 85, in run
    self.addActions()
  File "/home/kittens/utils/../modules/reporting/maec41.py", line 129, in addActions
    self.createProcessActions(process)
  File "/home/kittens/utils/../modules/reporting/maec41.py", line 653, in createProcessActions
    action_dict = self.apiCallToAction(call, pos)
  File "/home/kittens/utils/../modules/reporting/maec41.py", line 276, in apiCallToAction
    action_dict["associated_objects"] = self.processActionAssociatedObjects(mapping_dict["parameter_associated_objects"], parameter_list)
  File "/home/kittens/utils/../modules/reporting/maec41.py", line 381, in processActionAssociatedObjects
    self.processRegKeys(associated_objects_list)
  File "/home/kittens/utils/../modules/reporting/maec41.py", line 538, in processRegKeys
    associated_object = self.processRegKeyHandle(associated_object["properties"]["hive"], associated_object)
  File "/home/kittens/utils/../modules/reporting/maec41.py", line 558, in processRegKeyHandle
    self.processRegKeyHandle(handle_mapped_key["properties"]["hive"], current_dict)
.... about 2000 lines later: 
  File "/home/kittens/utils/../modules/reporting/maec41.py", line 558, in processRegKeyHandle
    self.processRegKeyHandle(handle_mapped_key["properties"]["hive"], current_dict)
  File "/home/kittens/utils/../modules/reporting/maec41.py", line 558, in processRegKeyHandle
    self.processRegKeyHandle(handle_mapped_key["properties"]["hive"], current_dict)
  File "/home/kittens/utils/../modules/reporting/maec41.py", line 558, in processRegKeyHandle
    self.processRegKeyHandle(handle_mapped_key["properties"]["hive"], current_dict)
  File "/home/kittens/utils/../modules/reporting/maec41.py", line 558, in processRegKeyHandle
    self.processRegKeyHandle(handle_mapped_key["properties"]["hive"], current_dict)
RuntimeError: maximum recursion depth exceeded
```

we seem to get them very about in 60-70 files 
any hints on providing a bit more helpful info to help diagnose the issue? E.g. I can put in a few interim debug statements into the MAEC reporting module ? 

thanks 
mb

**Comment by PingTrip** [comment]
I'm seeing the same issue as well, were you able to make any progress with your debugging?

**Comment by mallorybobalice** [comment]
unfortunately no - for the time being - maec reports are not really required for our use, so we've turned them off to save space and processing time. 

at a guess, you'd have to put a few print statements around formerly lines 538/558 to provide more info about what reg key or hive is causing the issue.
