### ISSUE TITLE
cuckoo web interface issues

### ISSUE THREAD

**Issue by adimenia** [spender-sandbox/cuckoo-modified#80]
just finishes installing cuckoo, and having issues starting the web interface.
here is the error message.

sudo /opt/cuckoo/web/manage.py runserver
Traceback (most recent call last):
File "/opt/cuckoo/web/manage.py", line 14, in 
execute_from_command_line(sys.argv)
File "/usr/local/lib/python2.7/dist-packages/django/core/management/init.py", line 338, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python2.7/dist-packages/django/core/management/init.py", line 303, in execute
settings.INSTALLED_APPS
File "/usr/local/lib/python2.7/dist-packages/django/conf/init.py", line 48, in getattr
self.setup(name)
File "/usr/local/lib/python2.7/dist-packages/django/conf/__init_.py", line 44, in setup
self.wrapped = Settings(settings_module)
File "/usr/local/lib/python2.7/dist-packages/django/conf/__init.py", line 92, in init
mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/lib/python2.7/importlib/init.py", line 37, in import_module
import(name)
File "/opt/cuckoo/web/web/settings.py", line 16, in 
from lib.cuckoo.common.config import Config
ImportError: No module named lib.cuckoo.common.config

**Comment by doomedraven** [comment]
just did git clone and fresh install and can't reproduce this bug

**Comment by KillerInstinct** [comment]
Looks like you're trying to run django from the wrong directory. cd'ing to CUCKOO_ROOT/web/ and running manage.py from there.
