### ISSUE TITLE
Error in processing module of Static

### ISSUE THREAD

**Issue by pashashocky** [spender-sandbox/cuckoo-modified#89]
```
2016-04-09 12:26:02,334 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Static":
Traceback (most recent call last):
  File "/var/cuckoo/cuckoo-live/utils/../lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/var/cuckoo/cuckoo-live/utils/../modules/processing/static.py", line 1277, in run
    static = PortableExecutable(self.file_path, self.results).run()
  File "/var/cuckoo/cuckoo-live/utils/../modules/processing/static.py", line 759, in run
    peresults["exported_dll_name"] = self._get_exported_dll_name()
  File "/var/cuckoo/cuckoo-live/utils/../modules/processing/static.py", line 338, in _get_exported_dll_name
    return convert_to_printable(self.pe.get_string_at_rva(self.pe.DIRECTORY_ENTRY_EXPORT.struct.Name))
  File "/var/cuckoo/cuckoo-live/utils/../lib/cuckoo/common/utils.py", line 137, in convert_to_printable
    if is_printable(s):
  File "/var/cuckoo/cuckoo-live/utils/../lib/cuckoo/common/utils.py", line 110, in is_printable
    if c not in PRINTABLE_CHARACTERS:
TypeError: 'in <string>' requires string as left operand, not int
```

I tried fixing it myself, but failed, and was getting more errors as a result.

**Comment by spender-sandbox** [comment]
What version of pefile are you using?

-Brad

**Comment by pashashocky** [comment]
$ pip show pefile
---
Name: pefile
Version: 2016.3.28

**Comment by spender-sandbox** [comment]
Can you give me the hash of the file (if it's on VT)?

Thanks,
-Brad

**Comment by Nadacsc** [comment]
I am having the exact same problem 
this is the file info that I've tried to analyse .. sample uploaded to malwr.com
https://malwr.com/analysis/Zjc1NGE2MmQ5MWE3NDk0Y2JiYzZiMTg3NTMxZjY3ZjE/

**Comment by pashashocky** [comment]
From my experience, this seems to only happen to DLL's, do you have any idea why this may be happening?

**Comment by spender-sandbox** [comment]
No problem here, this is a pefile bug that should be reported to the pefile upstream.  The code has been going through significant churn since the beginning of this year.  A current checked-out version of it won't even run on Python 2.7.  I would suggest simply using a version from last year for the time being.

-Brad
